### ISSUE TITLE
Following doctrine/registration_form.html Fails

### ISSUE THREAD

**Issue by develth** [symfony/symfony-docs#11885] opened 2019-07-04 09:22 UTC
Hello,

when following https://symfony.com/doc/current/doctrine/registration_form.html it will fail because of validation (data.password is not set). It seems like this new feature broke it:

https://symfony.com/blog/new-in-symfony-4-3-automatic-validation

**Comment by javiereguiluz** [comment] 2019-07-04 10:34
If that's the cause of the bug ... then it looks like a Symfony code bug and not something for Symfony Docs ... but maybe we can do something in docs? @xabbuh any idea? Thanks.

**Comment by develth** [comment] 2019-07-04 10:36
I just followed https://github.com/symfony/symfony/issues/32118 where it is a recommendation for create a issue here. 
I 'fixed' it by disabling the auto validation

**Comment by javiereguiluz** [comment] 2019-07-04 10:39
@develth you did right. Most of the times, when there's an error when following the docs, it's a docs issue. However, this time it may be related to the controversial new feature called "automatic validation" that you mentioned in the description. There are some issues about it https://github.com/symfony/symfony/issues/32070 including an option to disable it: https://github.com/symfony/symfony/pull/32107  So, this may be complicated. Maybe we need to update the docs, maybe Symfony must fix some code, maybe both. Thanks for your patience!

**Comment by xabbuh** [comment] 2019-07-04 10:43
This indeed the same issue that Ryan reported in symfony/symfony#32070. The only solution right now is to disable auto-validation.

**Comment by javiereguiluz** [comment] 2019-09-23 10:25
Let's close this because it's related to the mentioned Symfony issue ... and because we've reworded this article to remove all of its contents (because they were duplicated with other articles). Thanks.

**Closed by javiereguiluz** 2019-09-23 10:25 UTC
