### ISSUE TITLE
[Dotenv] Reimplementing symfony/flex' dump-env as a Symfony command

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#15878] opened 2021-09-30 13:41 UTC
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#42610
| PR author(s) | @abdielcs, @nicolas-grekas
| Merged in    | 5.4

**Comment by javiereguiluz** [comment] 2021-10-08 15:14
Not sure what to do here ... the new command is of course nice, but having to register it manually before using it feels cumbersome and weird. What do you think @symfony/team-symfony-docs? Should we stick to the previous command and not document this? Should we document this one in spite of the manual config? Thanks!

**Comment by nicolas-grekas** [comment] 2021-10-08 15:17
we could tell something about on deployment.rst and/or configuration.rst, where we tell about flex' `dump-env`

**Comment by mertingen** [comment] 2022-01-19 15:42
I can edit both if you give a green light. The change will be only regarding the commands. (If it works in the same way)
 The description is obvious.

"""
You might not want your application to process the .env.* files on every request. You can generate an optimized .env.local.php which overrides all other configuration files:

`php bin/console dotenv:dump prod
`
The generated file will contain all the configurations stored in .env. If you want to rely only on environment variables, generate one without any values using:

`php bin/console dotenv:dump prod --empty`
"""

**Comment by nicolas-grekas** [comment] 2022-01-19 15:46
please go ahead with a PR yes

**Comment by wouterj** [comment] 2022-01-19 16:06
The issue is that this command is not available by default (see the PR) - which means we need to document the set-up instructions somewhere.

If that's the way to go, we should document this in configuration only and reference it from deployments. However, if the Composer command is kept (I don't see it's deprecated?) I'm leaning towards just using that - the UX is much better.

**Comment by 94noni** [comment] 2022-08-02 21:30
can be closed I think, [related PR is merged](https://github.com/symfony/symfony-docs/pull/16611#issuecomment-1173897993)

**Closed as completed** 2022-08-02 22:06 UTC
Labels: hasPR, Dotenv
