### ISSUE TITLE
Reverse engineering in symfony 4

### ISSUE THREAD

**Issue by chiqui3d** [symfony/symfony-docs#9172] opened 2018-01-30 06:08 UTC
Hello, 
following the documentation steps and now everything could be centralized in the src folder.
Why doesn't this command work for me? I want to generate an entity and controller from a table.

`php bin/console doctrine:mapping:import --force App yml --filter="domains"
`

Error:

`Bundle "App" does not exist or it is not enabled. Maybe you forgot to add it in the registerBundles() method of your App\Kernel.php file?`

**Comment by javiereguiluz** [comment] 2018-02-02 07:40
@chiqui3d thanks for reporting this issue. The problem is that Doctrine is removing lots of features in their next 3.0 version, and this command is one of them. There's an attempt to fix it for Symfony 4 without bundles (see https://github.com/doctrine/DoctrineBundle/issues/736) but I don't know if it will be fixed. In any case, I'm going to add a caution note explaining that this doesn't work in bundle-less apps and that this feature will be completely removed soon. Thanks!

**Comment by chiqui3d** [comment] 2018-02-02 08:39
Thank you @javiereguiluz ,
I know you're working very hard. But it is very important to have these functions

Both to import from an existing database, as well as to generate the setters and getters of the entity.

I think that takes a lot of time, and having to do it by hand, in the times we are and in a Framework of such quality and magnitude, it would not be very logical to have an ORM that extends the working time.

I think I read in some issue that you were doing both commands for Maker Bundle, right?

**Comment by javiereguiluz** [comment] 2018-02-02 09:41
@chiqui3d the problem is that the Doctrine project is removing lots of features that were useful for a big part of the Symfony community, specially newcomers. They removed YAML mappings, the commands to generate entities, this command to reverse engineer databases, entity shortcuts in queries (like using `App:User` instead of `App\Entity\User`), etc.

Symfony is a different project than Doctrine and we don't have any control over those decisions. We're trying to mitigate some of them via the MakerBundle ... but this one about reverse engineering a database won't fit MakerBundle, which is focused on generating code without much complexity. I'm really sorry.

**Comment by chiqui3d** [comment] 2018-02-02 10:34
I understand, thank you.
But equally symfony should have its own ORM, as Laravel has or any other framework to help you better the code and the speed of work. DO NOT depend third party.

**Comment by javiereguiluz** [comment] 2018-02-02 12:38
Fixed by #9193.  @chiqui3d I agree with most of what you said :)

**Closed by javiereguiluz** 2018-02-02 12:38 UTC
