### ISSUE TITLE
SF4 + Bundle System?

### ISSUE THREAD

**Issue by jblac** [symfony/symfony-docs#14296] opened 2020-09-28 23:31 UTC
I'm a few years from using symfony, it seems a lot has changed since the last time I used it.  What exactly is the point of flex and the terrible new file structure?

What options are available for those of us who don't strive for laravel levels of mediocrity?   I'd like to use SF4 on a project, but not if I'm essentially just using laravel and forced to use annotations (which seriously, who's "bright" idea were these?)

**Comment by wouterj** [comment] 2020-09-29 08:34
Please refer to https://symfony.com/coc before you post anything new. The method of communication in the original comment is not even close to being respectful about others (not Symfony devs, not Laravel ones).

As for your question (which would be better suited for Slack - it's not a bug nor a feature request): Symfony 5 (or 4) is just as flexible as Symfony 2. Feel free not to use Flex and use the older file structure, if you feel like that's making everything greater.

**Comment by xabbuh** [comment] 2020-09-29 09:25
closing as explained by Wouter

**Closed by xabbuh** 2020-09-29 09:25 UTC
