### ISSUE TITLE
[Routing] Avoid double encoded slashes in query parameters

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#16578] opened 2022-03-08 15:08 UTC
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#45658
| PR author(s) | @usu
| Merged in    | 6.1

**Comment by javiereguiluz** [comment] 2022-03-11 16:24
Closing because this looks more like a bug fix. The PR changes are the expected behavior anyway and we don't document anything about the previous behavior. Thanks!

**Closed as completed by javiereguiluz** 2022-03-11 16:24 UTC
Labels: Routing
