### ISSUE TITLE
[Website] Docs index page temporarily returned an error 404

### ISSUE THREAD

**Issue by simonrjones** [symfony/symfony-docs#16382] opened 2022-01-09 12:51 UTC
Today I noticed the Symfony docs index page temporarily returned an error 404: https://symfony.com/doc/current/index.html

After chatting in Slack wirth @wouterj the page seemed to come back and return a 200. I'm logging this here in case it helps work out if there is some sort of server/caching configuration issue. I'm happy to help where I can (we use Cloudflare & Varnish caching at work), though I'm unaware of the symfony.com caching setup.

**Details**
I was checking the page via my browser around Sun, 09 Jan 2022 12:14 UTC and it returned a 404 for me for around 10 minutes.

I've noted a few possibly relevant HTTP response headers below from my requests (if you want all HTTP response headers let me know).

```
$ curl --HEAD https://symfony.com/doc/current/index.html
HTTP/2 404
date: Sun, 09 Jan 2022 12:14:28 GMT
age: 706
cache-control: public, s-maxage=708
x-content-digest: en2c7741e2e381211ff02daa6408c23c6d3c18d98e866db175b277a534096eb2d0
x-debug-info: eyJyZXRyaWVzIjowfQ==
x-platform-cache: EXPIRED
x-platform-cluster: lgei2rga6u3mm-master-7rqtwti
x-platform-processor: mso3wvcgfq4362basj2ljveqpa
x-platform-router: g3iqazcdo2xbnpwdfh436nvpna
x-request-id: 00-16c89929ab0cbfba952f7d2157828195-05d1457ff726e779-00
cf-cache-status: DYNAMIC
server: cloudflare
cf-ray: 6cad95e37a7476e4-LHR

$ curl --HEAD https://symfony.com/doc/current/index.html
HTTP/2 404
date: Sun, 09 Jan 2022 12:25:44 GMT
age: 706
cache-control: public, s-maxage=708
x-content-digest: en2c7741e2e381211ff02daa6408c23c6d3c18d98e866db175b277a534096eb2d0
x-debug-info: eyJyZXRyaWVzIjowfQ==
x-platform-cache: HIT
x-platform-cluster: lgei2rga6u3mm-master-7rqtwti
x-platform-processor: mso3wvcgfq4362basj2ljveqpa
x-platform-router: g3iqazcdo2xbnpwdfh436nvpna
x-request-id: 00-16c899c717ae4493bb932eaa006b2a5a-868c2cd4b69abee1-00
cf-cache-status: DYNAMIC
server: cloudflare
cf-ray: 6cada6654a8e4072-LHR

$ curl --HEAD https://symfony.com/doc/current/index.html
HTTP/2 404
date: Sun, 09 Jan 2022 12:26:11 GMT
age: 706
cache-control: public, s-maxage=708
x-content-digest: en2c7741e2e381211ff02daa6408c23c6d3c18d98e866db175b277a534096eb2d0
x-debug-info: eyJyZXRyaWVzIjowfQ==
x-platform-cache: HIT
x-platform-cluster: lgei2rga6u3mm-master-7rqtwti
x-platform-processor: mso3wvcgfq4362basj2ljveqpa
x-platform-router: g3iqazcdo2xbnpwdfh436nvpna
x-request-id: 00-16c899cd44c44b61ef7e395b70d02013-463a3b0d901f4712-00
cf-cache-status: DYNAMIC
server: cloudflare
cf-ray: 6cada70b2b1575bd-LHR

$ curl --HEAD https://symfony.com/doc/current/index.html
HTTP/2 200
date: Sun, 09 Jan 2022 12:26:52 GMT
age: 1080
cache-control: public, s-maxage=1585
x-content-digest: en90358faba47668f0964d80f55abf10a44e050915c77d5d3b7dba7ff7bc30963a
x-debug-info: eyJyZXRyaWVzIjowfQ==
x-platform-cache: EXPIRED
x-platform-cluster: lgei2rga6u3mm-master-7rqtwti
x-platform-processor: mso3wvcgfq4362basj2ljveqpa
x-platform-router: g3iqazcdo2xbnpwdfh436nvpna
x-request-id: 00-16c899d7030a00fd42f3e74431d0d7be-0bbbf537053be454-00
cf-cache-status: DYNAMIC
server: cloudflare
cf-ray: 6cada810a9f6f3f7-LHR

$ curl --HEAD https://symfony.com/doc/current/index.html
HTTP/2 200
date: Sun, 09 Jan 2022 12:27:07 GMT
age: 1080
cache-control: public, s-maxage=1585
x-content-digest: en90358faba47668f0964d80f55abf10a44e050915c77d5d3b7dba7ff7bc30963a
x-debug-info: eyJyZXRyaWVzIjowfQ==
x-platform-cache: HIT
x-platform-cluster: lgei2rga6u3mm-master-7rqtwti
x-platform-processor: mso3wvcgfq4362basj2ljveqpa
x-platform-router: g3iqazcdo2xbnpwdfh436nvpna
x-request-id: 00-16c899da68d898a85e5a904b01df7711-9b1e3cf4ba0216d4-00
cf-cache-status: DYNAMIC
server: cloudflare
cf-ray: 6cada86bdccf773e-LHR
```

**Comment by wouterj** [comment] 2022-01-09 13:30
cc @javiereguiluz

**Comment by wouterj** [comment] 2022-01-09 13:31
Thanks for the detailed report btw! Hopefully this will help the symfony.com team with debugging

**Comment by javiereguiluz** [comment] 2022-01-25 16:13
@simonrjones thanks for reporting! This was probably some temporary issue while deploying some fixes. Sorry about that!

I can't reproduce it anymore, so let's close it.

**Closed as completed by javiereguiluz** 2022-01-25 16:13 UTC
Labels: Website
