### ISSUE TITLE
[Website] Quick search appears holding down shift (not just double tap)

### ISSUE THREAD

**Issue by jennevdmeer** [symfony/symfony-docs#16756] opened 2022-04-27 11:06 UTC
As the title suggests the quick search bar appears when you hold down the shift button for a longer period. I'm using windows/chrome but i assume it is common across all browsers.

My biggest problem with this is that when you hold down shift and try to select/manipulate an existing selection of text (for me usually within code blocks) the search pops up because I am holding down the shift button which just blocks the ability to select any content in that matter.

**Comment by javiereguiluz** [comment] 2023-02-10 15:36
Sorry I never replied on time 🙏 

I can't reproduce this with Firefox or Chrome. If I just press `Shift` indefinitely, the search modal doesn't appear. I must press `Shift` twice to show it. I'm closing as "fixed", but if you can still reproduce it, please tell us the steps in detail so we can debug it. Thanks!

**Comment by jennevdmeer** [comment] 2023-02-13 14:13
Not doing anything special, just on the homepage holding down my shift button. Might be a Windows thing? My colleagues computer does the same thing. Also tested it and it behaves the same way in Chrome, Edge and Firefox.

Some further testing it just sends multiple key strokes (onkeydown when holding). Seems it can be solved using this flag https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/repeat

https://user-images.githubusercontent.com/310006/218481121-eadeddef-7302-40fa-a8c7-a0c27391925f.mp4
* *the selecting isn't needed for the triggering, just showing an example of what i was trying to do*

**Comment by javiereguiluz** [comment] 2023-02-13 14:58
Thanks for the additional insights. Let's reopen this.

By the way, we use this JS library to handle key presses: https://github.com/ccampbell/mousetrap

**Comment by javiereguiluz** [comment] 2023-05-05 15:39
Let's close this again. Sadly we can't do much about this. We use a third-party library and it doesn't include any setting to configure this. We don't have resources to do this manually or switch to another library, so let's close as "won't fix".

I'm sorry about this 🙏 but I hope you understand this decision. Thanks.

**Closed as completed by javiereguiluz** 2023-05-05 15:39 UTC
Labels: Website
