### ISSUE TITLE
The info icon looks weird on DomCrawler Doc (nested problem?!)

### ISSUE THREAD

**Issue by OskarStark** [symfony/symfony-docs#5700] opened 2015-09-18 09:44 UTC
<img width="765" alt="bildschirmfoto 2015-09-18 um 11 43 15" src="https://cloud.githubusercontent.com/assets/995707/9956631/878f04d2-5dfa-11e5-9e3c-924f9a73ef21.png">

URL:
http://symfony.com/doc/current/components/dom_crawler.html#adding-the-content

**Comment by stof** [comment] 2015-09-18 09:48
What are you finding weird ?

**Comment by OskarStark** [comment] 2015-09-18 09:53
sorry... i mean the icon
<img width="163" alt="bildschirmfoto 2015-09-18 um 11 52 50" src="https://cloud.githubusercontent.com/assets/995707/9956804/d261eece-5dfb-11e5-92e4-b844d7270dff.png">

**Comment by OskarStark** [comment] 2015-09-18 09:53
i updated the title @stof

**Comment by stof** [comment] 2015-09-18 09:54
@javiereguiluz this is a website issue. Can you check it ?

**Comment by javiereguiluz** [comment] 2015-09-18 10:34
@OskarStark thanks for reporting this issue. However, this is a duplicate of #4783. I'll fix it eventually, but it's very low in my TODO list to be honest.

**Comment by OskarStark** [comment] 2015-09-18 11:16
thank you @javiereguiluz , i think it's an edge case, but i wanted to report that issue

**Comment by xabbuh** [comment] 2015-09-23 20:13
closing here as a duplicate of #4783

**Closed by xabbuh** 2015-09-23 20:13 UTC
