### ISSUE TITLE
"Create your First Page in Symfony" instructions don't work using Symfony Docker

### ISSUE THREAD

**Issue by linkedupbits** [symfony/symfony-docs#18405] opened 2023-06-13 04:47 UTC
I am trying to follow the "hello world" example at https://symfony.com/doc/current/page_creation.html#creating-a-page-route-and-controller using a docker image, and it doesn't work - when I view the page in the browser I get:

> The controller for URI "/lucky/number" is not callable: Controller "App\Controller\LuckyController" cannot be fetched from the container because it is private. Did you forget to tag the service with "controller.service_arguments"?

I have:
 - cloned https://github.com/dunglas/symfony-docker
 - build the images and started the containers
 - added a new file src/Controller/LuckyController.php (with contents as per the example)
 - edited the existing config/routes.yaml
 - tried browsing the page

Is there something obvious I am missing?

I have also tried the [annotations](https://symfony.com/doc/current/page_creation.html#annotation-routes) and that has errors with the route not working.

**Comment by maxhelias** [comment] 2023-06-13 05:48
I think you're missing the `#[AsController]` in your class and even in the documentation 😅

**Comment by alexandre-daubois** [comment] 2023-06-13 07:53
I just tried and wasn't able to reproduce. Could you maybe link a repo so we're able to test your reproducer and be sure we have the same code?

**Comment by linkedupbits** [comment] 2023-06-13 08:25
steps to reproduce:

delete all images and containers in docker desktop for good measure...

Terminal 1:
``` bash

git clone https://github.com/dunglas/symfony-docker
cd symfony-docker
docker compose build --pull --no-cache
docker compose up
```

Terminal 2:
``` bash
docker exec -it symfony-docker-php-1 /bin/sh
apk add vim
vim /srv/app/src/Controller/LuckyController.php
vim /srv/app/config/routes.yaml 
```

src/Controller/LuckyController.php
``` php
// src/Controller/LuckyController.php
namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;

class LuckyController
{
    public function number(): Response
    {
        $number = random_int(0, 100);

        return new Response(
            '<html><body>Lucky number: '.$number.'</body></html>'
        );
    }
}
```

src/config/route.yaml
``` yaml
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# the "app_lucky_number" route name is not important yet
app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number
```

**Comment by linkedupbits** [comment] 2023-06-13 09:40
Note - this is after editing the LuckyController.php to try adding abstract controller etc...

``` bash
/srv/app # php bin/console about
declare(strict_types=1);
// src/Controller/LuckyController.php
namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[AsController]
class LuckyController extends AbstractController
{
    public function number(): Response
    {
        $number = random_int(0, 100);

        return new Response(
            '<html><body>Lucky number: '.$number.'</body></html>'
        );
    }
}
 -------------------- --------------------------------- 
  Symfony                                               
 -------------------- --------------------------------- 
  Version              6.3.0                            
  Long-Term Support    No                               
  End of maintenance   01/2024 (in +232 days)           
  End of life          01/2024 (in +232 days)           
 -------------------- --------------------------------- 
  Kernel                                                
 -------------------- --------------------------------- 
  Type                 App\Kernel                       
  Environment          dev                              
  Debug                true                             
  Charset              UTF-8                            
  Cache directory      ./var/cache/dev (310 KiB)        
  Build directory      ./var/cache/dev (310 KiB)        
  Log directory        ./var/log (0 B)                  
 -------------------- --------------------------------- 
  PHP                                                   
 -------------------- --------------------------------- 
  Version              8.2.7                            
  Architecture         64 bits                          
  Intl locale          en_US_POSIX                      
  Timezone             UTC (2023-06-13T09:37:50+00:00)  
  OPcache              true                             
  APCu                 true                             
  Xdebug               true                             
 -------------------- --------------------------------- 

/srv/app # 
```

**Comment by linkedupbits** [comment] 2023-06-13 09:43
Why does this keep echoing the controller file?

``` bash
/srv/app # php bin/console debug:router
declare(strict_types=1);
// src/Controller/LuckyController.php
namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[AsController]
class LuckyController extends AbstractController
{
    public function number(): Response
    {
        $number = random_int(0, 100);

        return new Response(
            '<html><body>Lucky number: '.$number.'</body></html>'
        );
    }
}
declare(strict_types=1);
// src/Controller/LuckyController.php
namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[AsController]
class LuckyController extends AbstractController
{
    public function number(): Response
    {
        $number = random_int(0, 100);

        return new Response(
            '<html><body>Lucky number: '.$number.'</body></html>'
        );
    }
}
declare(strict_types=1);
// src/Controller/LuckyController.php
namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[AsController]
class LuckyController extends AbstractController
{
    public function number(): Response
    {
        $number = random_int(0, 100);

        return new Response(
            '<html><body>Lucky number: '.$number.'</body></html>'
        );
    }
}
declare(strict_types=1);
// src/Controller/LuckyController.php
namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[AsController]
class LuckyController extends AbstractController
{
    public function number(): Response
    {
        $number = random_int(0, 100);

        return new Response(
            '<html><body>Lucky number: '.$number.'</body></html>'
        );
    }
}
 ------------------ -------- -------- ------ -------------------------- 
  Name               Method   Scheme   Host   Path                      
 ------------------ -------- -------- ------ -------------------------- 
  _preview_error     ANY      ANY      ANY    /_error/{code}.{_format}  
  app_lucky_number   ANY      ANY      ANY    /lucky/number             
 ------------------ -------- -------- ------ -------------------------- 

/srv/app # 

```

**Comment by alexandre-daubois** [comment] 2023-06-13 09:53
It seems you're missing the php opening tag on top of your file, you may try to add `<?php` on the first line

**Comment by linkedupbits** [comment] 2023-06-13 10:09
> It seems you're missing the php opening tag on top of your file, you may try to add `<?php` on the first line

You are exactly right - I had just found that and was returning to comment.

Shouldn't that be included in the source in the example, or is there a php convention it is not included when providing source ?

**Comment by alexandre-daubois** [comment] 2023-06-13 10:29
Because this tag **must** be present in all PHP files, I guess the doc team decided it is not necessary to put it in each and every example of the documentation 🙂

**Comment by javiereguiluz** [comment] 2023-06-22 10:37
Yes, Alex is right. We discussed about this in the past (many times) and the decision was:

* To never include this opening tag in the examples ...
* ... but include it only in a few examples of some special docs targeted at newcomers

So, generally speaking, we don't include that opening tag.

-----

Apart from that ... do we miss the `#[AsController]` attribute or anything else in this example?

**Comment by javiereguiluz** [comment] 2023-07-05 07:39
I'm closing this as fixed because the code shown in the example of this page works as expected. So, hopefully the issue was just the missing `<?php` opening tag when copying code. Thanks.

**Closed as completed by javiereguiluz** 2023-07-05 07:39 UTC
