### ISSUE TITLE
Documentation not being built (properly)

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#5902] opened 2015-11-24 21:17 UTC
It seems that the documentation is not being rebuilt anymore (see https://github.com/symfony/symfony-docs/pull/5876#issuecomment-158899283).

Furthermore, we do not have any separate `2.8` version rendered on symfony.com.

ping @javiereguiluz

**Comment by javiereguiluz** [comment] 2015-11-25 09:50
I'm looking into the error. And the 2.8 version should be enabled soon.

**Comment by javiereguiluz** [comment] 2015-11-27 11:08
We finally fixed this error. The problem is that the server was using an outdated Sphinx version which didn't support these recently introduced values for the `ConfigurationBlock` directive:

```diff
+        'twig':            'Twig',
+        'html+twig':       'Twig',
+        'twig+html':       'Twig',
```

We'll need to wait a few minutes/hours until everything is rebuilt.

**Comment by xabbuh** [comment] 2015-11-27 11:47
@javiereguiluz Thanks for investigating. Will it be possible to see build errors on http://symfony.com/doc/build_errors again?

**Comment by weaverryan** [comment] 2015-11-27 19:22
Thanks @javiereguiluz, let's watch this closely. I just merge microkernel and Guard (and will merge more soon). So as long as this is building before next week, we're in great shape.

**Comment by WouterJ** [comment] 2015-11-28 01:13
Closing as the build proces seems to work again (e.g. http://symfony.com/doc/2.8/cookbook/configuration/micro-kernel-trait.html)

Thanks @javiereguiluz !

**Closed by WouterJ** 2015-11-28 01:13 UTC
Labels: Website

**Comment by xabbuh** [comment] 2015-11-28 08:56
Hoorary! :) Thanks Javier.
