### ISSUE TITLE
Change in EventDispatcher::dispatch parameters not reflected

### ISSUE THREAD

**Issue by finwe** [symfony/symfony-docs#11628] opened 2019-05-30 10:12 UTC
Based on https://github.com/symfony/symfony/pull/28920 parameter calls should be reversed in documentation.

Furthermore, in 4.3, EventDispatcher lost its dispatch method $eventName parameter - it is commented out in the source https://github.com/symfony/symfony/blob/4.3/src/Symfony/Component/EventDispatcher/EventDispatcher.php - I guess this is a bug? Should I report an issue in the main repo?

**Comment by chalasr** [comment] 2019-05-30 21:00
It is not a bug but a compatibility layer required for the change you linked. The argument will be uncommented in 5.0. So no, no report needed :)

But 👍 for this issue, we need that change to be documented.

**Comment by finwe** [comment] 2019-06-02 12:09
Thanks, this leads me to two more questions:

* Isn't this a breaking change for EventDispatcher 4.3 vs 4.2, removing a parameter?
* I've run into `Argument 1 passed to "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" must be an instance of Symfony\Component\EventDispatcher\Event <event class> given` When I extend from `Contract` namespace in Symfony 4.3 as noted in deprecation comment - How is that not a bug?

**Comment by xabbuh** [comment] 2019-06-14 08:41
@finwe Please open a new issue in the code repository if you think that you found a BC break that needs to be fixed.

**Comment by javiereguiluz** [comment] 2020-07-10 14:11
Let's close this as fixed because, at least starting from 4.4, all `dispatch()` examples use the new signature (eventObject, eventName). Thanks!

**Closed by javiereguiluz** 2020-07-10 14:11 UTC
Labels: EventDispatcher
