### ISSUE TITLE
[Notifier] Fail link for documentation.

### ISSUE THREAD

**Issue by Yozhef** [symfony/symfony-docs#12691] opened 2019-11-25 11:50 UTC
In Component Notifier documentation links to a non-existent page.

**Comment by wouterj** [comment] 2019-11-25 12:00
Yes, this is correct. Unfortunately, there is no documentation for this component yet. @TheGarious started working on it in https://github.com/symfony/symfony-docs/pull/12678 . Feel free to help :)

**Comment by wouterj** [comment] 2019-11-25 12:01
closing as duplicate of #12430

**Closed by wouterj** 2019-11-25 12:01 UTC
