### ISSUE TITLE
[Databases] Example code for "Automatically Fetching Objects (ParamConverter)" is not clear

### ISSUE THREAD

**Issue by msheakoski** [symfony/symfony-docs#9550] opened 2018-04-04 15:50 UTC
The [Automatically Fetching Objects (ParamConverter)](https://symfony.com/doc/current/doctrine.html#automatically-fetching-objects-paramconverter) section is confusing because it is not clear that you need to import the "FrameworkExtraBundle Route" annotation to get that functionality and if you are modifying an existing class, it may already be using the "Routing Component Route". It should be added to the example in the form of a diff like:
```diff
// Switch your imported Route annotation
-use Symfony\Component\Routing\Annotation\Route;
+use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
```
(something similar to the [PostCSS and autoprefixing](http://symfony.com/doc/current/frontend/encore/postcss.html) example code)

**Comment by xabbuh** [comment] 2018-04-05 09:36
I think this should rather be reported in the SensioFrameworkExtraBundle repository as that is where this part of the documentation is maintained.

**Comment by msheakoski** [comment] 2018-04-06 07:48
My apologies, I assumed that it was part of the symfony-docs project. I moved the relevant part over to the other repo. The database docs can still benefit from adding a "use" for the correct Route annotation, so I left that part open.

**Comment by msheakoski** [comment] 2018-04-07 16:06
Ahh, perhaps I misunderstood how the annotations work. Are annotations global, as in two annotations with the same name will overwrite each other? I thought they were scoped to the file that they were being imported into?

**Comment by xabbuh** [comment] 2018-04-09 08:11
I am not sure I understand what you mean. Could you maybe give an example that you tried, but that did not work as you expected it?

**Comment by javiereguiluz** [comment] 2018-07-16 15:24
I'm closing here because I can't reproduce the issue. The object ParamConverter works with the new `@Route` annotation (I'm not 100% sure, but I think they are completely unrelated). If you have more details about how to reproduce this, please share them and we'll reopen. Thanks!

**Closed by javiereguiluz** 2018-07-16 15:24 UTC
