### ISSUE TITLE
Missing service definition from "Lazy Services" page

### ISSUE THREAD

**Issue by SoboLAN** [symfony/symfony-docs#5930] opened 2015-11-29 16:41 UTC
The problem is on [this page](http://symfony.com/doc/master/components/dependency_injection/lazy_services.html):

![lazy services doc bug](https://cloud.githubusercontent.com/assets/6078542/11458437/98de222a-96c8-11e5-8194-dde34309a6cc.png)

The definition for the `foo` service is missing.

This appears the same on all versions of the page (for 2.3, 2.6 etc.).

**Comment by javiereguiluz** [comment] 2015-11-29 16:46
@SoboLAN thanks for reporting this error. In fact, at the moment lots of code blocks are missing in the Symfony docs. We're really sorry about this issue and we're working to fix it.

**Comment by WouterJ** [comment] 2015-11-29 17:10
Closing as duplicate of #5918 . Thanks for reporting it though!

**Closed by WouterJ** 2015-11-29 17:10 UTC

**Comment by SoboLAN** [comment] 2015-11-29 18:14
@javiereguiluz Thanks for your reply.

@WouterJ Thank you too. I would mark #5918 with a "Crtical" tag, or something similar ;) .
