### ISSUE TITLE
Tab is not aligned with content block in Documentation pages

### ISSUE THREAD

**Issue by irfanmomin** [symfony/symfony-docs#5687] opened 2015-09-10 09:32 UTC
Please see attached file, there is misalignment between first tab and content block. This is found in symfony 2.x documentation:
http://symfony.com/doc/current/book/page_creation.html#dynamic-url-patterns-lucky-number-count
and might be possible on other pages too.
OS: Ubuntu 12.04 / Browser: Mozilla v40.0.3
OS: Windows 8 / Browser: IE 9 to IE 11
OS: Windows 8 / Browser: Mozilla v40.0.3
Thanks.

![create your first page in symfony the symfony book 2015-09-10 14-44-36](https://cloud.githubusercontent.com/assets/6543265/9784926/16f2e7cc-57cc-11e5-855a-f0eeca59a1db.png)

**Comment by javiereguiluz** [comment] 2015-09-10 09:41
@irfanmomin thanks for reporting this issue and for providing such a detailed information.

In the past, some users like @WouterJ (which uses Windows), reported similar issues. The problem is that I can only test the design on Mac OS and there I can't reproduce the error.

Could you please test if changing the `margin-left` to `8px` on `div.jsactive li` solves your problem?

![symfony_doc_alignment](https://cloud.githubusercontent.com/assets/73419/9785211/d9b606ac-57b0-11e5-859b-d2c01a73f406.png)

**Comment by irfanmomin** [comment] 2015-09-10 09:45
Yeah exactly..!
I have checked with changing 'margin-left' to 8px
Looking perfect!

**Comment by javiereguiluz** [comment] 2015-09-10 09:50
@irfanmomin OK, but the problem is that using `8px` unaligns it for Mac OS users ... an we all know how picky they are for design-related issues. I'm going to fix it in a different way.

**Comment by irfanmomin** [comment] 2015-09-10 09:52
Yeah sure!
Thanks.

**Comment by javiereguiluz** [comment] 2015-09-10 10:13
@irfanmomin I've fixed it locally applying this change:

![code_change](https://cloud.githubusercontent.com/assets/73419/9785790/2d633cda-57b5-11e5-97ce-5533a5948103.png)

This will be fixed in symfony.com server after the usual review/merge/deploy process.

**Comment by irfanmomin** [comment] 2015-09-10 10:25
**Great!** @javiereguiluz 
But as you have show me changes, i have applied on ubuntu 12.04 / Mozilla v40.0.3
Not looking solved!

Kindly give me URL after changes applied.

**Comment by javiereguiluz** [comment] 2015-09-10 10:45
Could you please perform another test? In addition to the above changes, could you apply `box-sizing: border-box;` to the `.literal-block .highlighttable td.linenos` selector? Thanks!

**Comment by irfanmomin** [comment] 2015-09-10 10:47
@javiereguiluz 
Let me check for same. :+1:

**Comment by WouterJ** [comment] 2015-09-10 10:49
@javiereguiluz it seems like an Firefox/IE problem here (Chrome works perfectly). The problem is that the line number box is widther in Firefox. I suspect this is a problem in the implementation of the box sizing model (which is still in beta).

**Comment by irfanmomin** [comment] 2015-09-10 10:52
@WouterJ 
Exactly! This issue is not producing in Chrome.

**Closed** 2016-02-28 16:28 UTC
Labels: Website
