### ISSUE TITLE
missing api doc [master/3.0]

### ISSUE THREAD

**Issue by Hanmac** [symfony/symfony-docs#5983] opened 2015-12-08 13:11 UTC
many things are missing from the api.symfony.com

missing ChoiceLoaderInterface:
http://symfony.com/doc/master/reference/forms/types/choice.html does link to
http://api.symfony.com/master/Symfony/Component/Form/ChoiceList/Loader/ChoiceLoaderInterface.html

http://symfony.com/doc/master/components/serializer.html does link to:
http://api.symfony.com/master/Symfony/Component/Serializer/Normalizer/ArrayDenormalizer.html
http://api.symfony.com/master/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.html

many doc/current does link to api.symfony.com/3.0 which does not exist yet.

http://symfony.com/doc/current/components/serializer.html does link to:
http://api.symfony.com/3.0/Symfony/Component/Serializer/Normalizer/AbstractNormalizer.html
http://api.symfony.com/3.0/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.html
http://api.symfony.com/3.0/Symfony/Component/Serializer/Normalizer/GetSetMethodNormalizer.html
http://api.symfony.com/3.0/Symfony/Component/Serializer/Normalizer/PropertyNormalizer.html
http://api.symfony.com/3.0/Symfony/Component/Serializer/Exception/CircularReferenceException.html
http://api.symfony.com/3.0/Symfony/Component/Serializer/Normalizer/ArrayDenormalizer.html
http://api.symfony.com/3.0/Symfony/Component/Serializer/Mapping/Factory/ClassMetadataFactory.html
http://api.symfony.com/3.0/Symfony/Component/Serializer/NameConverter/NameConverterInterface.html
http://api.symfony.com/3.0/Symfony/Component/Serializer/NameConverter/CamelCaseToSnakeCaseNameConverter.html

http://symfony.com/doc/current/reference/forms/types/choice.html does link to:
http://api.symfony.com/3.0/Symfony/Component/Form/Extension/Core/Type/ChoiceType.html
http://symfony.com/doc/current/reference/forms/types/country.html does link to:
http://api.symfony.com/3.0/Symfony/Component/Form/Extension/Core/Type/CountryType.html

**Comment by ogizanagi** [comment] 2015-12-08 13:14
duplicate of #5975

**Comment by xabbuh** [comment] 2015-12-09 11:08
Thanks for reporting this @Hanmac. I'm anyway closing this as a duplicate of #5975.

**Closed by xabbuh** 2015-12-09 11:08 UTC
