### ISSUE TITLE
Links using http protocol => Blank page: Content Encoding Error

### ISSUE THREAD

**Issue by alexandre-le-borgne** [symfony/symfony-docs#9409] opened 2018-03-07 15:31 UTC
Links using the http protocol instead of the https protocol are present in many places in the documentation. Some of these http links lead to a blank page or an error message:

(Example on firefox)

> 
> Content encoding error
> 
> The page you are trying to view can not be displayed because it uses an invalid or unsupported compression type.
> 
>      Please contact the owners of the website to inform them of this problem.

Bug also present on chrome. You can find such a link in the section "Using Configuration to Change the Services" of this page : 
http://symfony.com/doc/current/bundles/extension.html

> How to Create Friendly Configuration for a Bundle 

is a link to : http://symfony.com/doc/current/bundles/configuration.html

**Comment by javiereguiluz** [comment] 2018-03-07 15:37
I'm afraid I can't reproduce this error. Do you work in a place where a proxy is used? Maybe that proxy is blocking your http URLs but not the https ones. I can browse both without problems.

**Comment by alexandre-le-borgne** [comment] 2018-03-07 15:39
Yes it is, but the problem only occurs for Symfony and on some urls. Others also in http on the symfony documentation works fine.

**Comment by xabbuh** [comment] 2018-03-08 07:25
@alexandre-le-borgne If you visit https://symfony.com/doc/current/bundles/extension.html instead, you will also get a link https://symfony.com/doc/current/bundles/configuration.html. I don't think we have any hardcoded links to HTTP sites when HTTPS is available. But we would gladly merge any PRs fixing existing links if there are some. I am closing here as there doesn't seem to be anything to do.

**Closed by xabbuh** 2018-03-08 07:25 UTC
Labels: Waiting feedback, Website
