### ISSUE TITLE
How to test unused private services

### ISSUE THREAD

**Issue by komik966** [symfony/symfony-docs#9890] opened 2018-06-06 13:10 UTC
In Symfony 4.1 appeared nice feature: https://symfony.com/blog/new-in-symfony-4-1-simpler-service-testing
As mentioned https://github.com/symfony/symfony/pull/26499#issuecomment-372628598 removing unused private services from `test.service_container` is intended behaviour.

In my bundle (call it *bundle A*) I've private service which will be type-hinted in other bundles, but not in *bundle A*.
Is there optimal way to  write tests for this service in *bundle A*?

**Comment by nicolas-grekas** [comment] 2018-07-01 08:47
Hi, yes: in your test configuration you can create a public alias to this service, then access it through this alias. I'd recommend to name the alias by prefixing the aliased service with the `test.` prefix.
Doc PR welcome if you'd like to improve it.

**Comment by HeahDude** [comment] 2018-07-01 15:43
Closing as duplicate of #8097. Thanks!

**Closed by HeahDude** 2018-07-01 15:43 UTC
Labels: Actionable, Testing
