### ISSUE TITLE
Add docs about framework->http_cache

### ISSUE THREAD

**Issue by alex-bacart** [symfony/symfony-docs#15245] opened 2021-04-16 09:10 UTC
The Fast Track book mentions a parameter `http_cache` https://symfony.com/doc/current/the-fast-track/en/21-cache.html#activating-the-symfony-http-cache-kernel

But it’s not listed in a Framework Configuration Reference https://symfony.com/doc/current/reference/configuration/framework.html

**Comment by javiereguiluz** [comment] 2021-04-22 09:09
You are right ... but this will be documented when completing #13881 ... so, we're closing this as a duplicate of it. Thanks!

**Closed as completed by javiereguiluz** 2021-04-22 09:09 UTC
