### ISSUE TITLE
[Routing] Example checking if a route path exists

### ISSUE THREAD

**Issue by ytilotti** [symfony/symfony-docs#16874] opened 2022-06-14 07:00 UTC
I think can be benefic to add information on `$this->router->match()` on this documentation [part](https://symfony.com/doc/current/routing.html#checking-if-a-route-exists).
There is an exemple with `$this->router->generate()` for route name & params. But add a way to match with the route path is important, especially with this information:

> In those cases, don't use the [getRouteCollection()](https://github.com/symfony/symfony/blob/6.1/src/Symfony/Component/Routing/Router.php#method_getRouteCollection) method because that regenerates the routing cache and slows down the application

What do you think? I haven't found any documentation on match.

**Comment by javiereguiluz** [comment] 2023-05-05 15:37
Thanks for this suggestion. Sorry we didn't answer on time.

The problem is that `match()` and `matchRequest()` call `getMatcher()` which in turns call this:

https://github.com/symfony/symfony/blob/a0b89b6f855b2505e0907ccfc7ec5f2f30952602/src/Symfony/Component/Routing/Router.php#L250

In the docs we say hat `$this->getRouteCollection();` shouldn't be used because it hurts performance a lot, so I think we shouldn't mention these methods either.

That's why we're closing this. Thanks!

**Closed as completed by javiereguiluz** 2023-05-05 15:37 UTC
Labels: Routing
