### ISSUE TITLE
Image in Upgrade Major is 404

### ISSUE THREAD

**Issue by ericpoe** [symfony/symfony-docs#9391] opened 2018-03-05 04:43 UTC
The image in [Upgrading a Major Version (e.g. 3.4.0 to 4.0.0)](https://symfony.com/doc/current/setup/upgrade_major.html) returns an HTTP 404 error. The page appears to be trying to load https://symfony.com/doc/current/_images/deprecations-in-profiler.png.html.

**Minor troubleshooting step:** I attempted to reach the image via https://symfony.com/doc/current/_images/deprecations-in-profiler.png and https://symfony.com/doc/current/_images/install/deprecations-in-profiler.png with the same 404. Yet I see it in the repo at https://github.com/symfony/symfony-docs/blob/master/_images/install/deprecations-in-profiler.png

**Comment by no-one** [comment] 2018-03-05 20:32
There seem to be more broken images, for example `../_images/xkcd-full.png` at https://symfony.com/doc/current/introduction/http_fundamentals.html (4.0 version).

**Comment by BonnieDoug** [comment] 2018-03-06 09:51
From what I can tell, all documentation images are broken. Also found on these pages:

* https://symfony.com/doc/current/quick_tour/the_big_picture.html
* https://symfony.com/doc/current/controller/error_pages.html

**Comment by andyexeter** [comment] 2018-03-06 15:21
Duplicate of #9349

**Comment by javiereguiluz** [comment] 2018-03-06 15:24
Closing as duplicate. We're sorry.

**Closed by javiereguiluz** 2018-03-06 15:24 UTC
Labels: Website
