### ISSUE TITLE
[Form] `label_html` is missing on ChoiceType

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony-docs#15291] opened 2021-04-24 19:12 UTC
The information from https://github.com/symfony/symfony-docs/pull/13316/files is missing at https://symfony.com/doc/current/reference/forms/types/choice.html

It is present on https://symfony.com/doc/current/reference/forms/types/form.html#label-html, but not passed through to ChoiceType's inherited options.

For the fact that `label_html` does also apply to `ChoiceType`, see https://github.com/symfony/symfony/issues/40806#issuecomment-824649973

**Comment by javiereguiluz** [comment] 2021-05-28 15:38
Thanks for reporting this. You are right. The problem is that we manage these "inherited options" manually, so there are many missing options.

"Soon" we're going to start using a different tool to build docs and it will allow to automate certain things. Including all the right "inherited options" automatically in all form types is one of those tasks. IT's already in our internal roadmap, so I'm going to close this one and hopefully will be fixed "soon". Thanks!

**Closed as completed** 2021-05-28 15:41 UTC
Labels: Form

**Comment by sandoba** [comment] 2022-07-11 13:32
Hello! Is there an update for this issue? I just noticed that even though "**label_html**" was first mentioned at
https://symfony.com/blog/new-in-symfony-5-1-form-improvements
about 2 years ago so far it is only listed at
https://symfony.com/doc/current/reference/forms/types/form.html#label-html
for the basic **FormType** and at 
https://symfony.com/doc/current/reference/forms/types/button.html#label-html
specifically for the **ButtonType**.

But it's ambiguous why the build process for the documentation lists this inherited option for
https://github.com/symfony/symfony-docs/blob/6.1/reference/forms/types/button.rst
but not for e.g.
https://github.com/symfony/symfony-docs/blob/6.1/reference/forms/types/text.rst

This is the case for many form types and likely true for other options of these form types as well but we can't fix this here by modifying the RST files.

(Easiest way to find missing options would probably be to compare the output of e.g. "symfony console debug:form TextType" with the generated HTML for https://symfony.com/doc/current/reference/forms/types/text.html)
