### ISSUE TITLE
[HttpClient] Remove credentials from requests redirected to same host b…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#16564] opened 2022-03-04 06:55 UTC
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#45616
| PR author(s) | @GromNaN
| Merged in    | 6.1

**Comment by javiereguiluz** [comment] 2022-03-24 16:43
Closing because this is an internal detail and the change is to comply with the HTTP standard, so it's the expected behavior.

**Closed as completed by javiereguiluz** 2022-03-24 16:43 UTC
Labels: HttpClient
