### ISSUE TITLE
Link for documentation page of DotEnv Component  returns 404 Not Found

### ISSUE THREAD

**Issue by felipsmartins** [symfony/symfony-docs#7526] opened 2017-02-23 13:53 UTC
Browsing to DotEnv Component doc deals with a 404 page not found.
 How to reproduce:

1. Go to http://symfony.com/ 
2. Click on the *Browse components* link
3. Go to *Component List* and click on *Dotenv* (you could to click on the link in the third column for docs and it has the same effect - 404)

Now in the Dotenv component main page click on **Documentation**. It returns a 404 Not Found.

![selecao_109](https://cloud.githubusercontent.com/assets/454116/23261705/5ad69e42-f9b6-11e6-81ee-b2efa3a2d45d.png)

### Note 
Swapping **current** segment of URL to **master** it works.

![selecao_110](https://cloud.githubusercontent.com/assets/454116/23261738/83015984-f9b6-11e6-97fa-327742a7329f.png)

**Comment by javiereguiluz** [comment] 2017-02-23 14:01
Yes, the problem is exactly what you said: `current` today points to 3.2, but DotEnv only exists in 3.3+

Should we remove this component until May 2017 when `current` turns into 3.3?

**Comment by javiereguiluz** [comment] 2017-03-04 14:41
I'm trying to fix this via https://github.com/symfony/symfony-marketing/pull/381

**Comment by iltar** [comment] 2017-03-04 14:57
Can't it automatically create a link to the version that _is_ available? A master version should _always_ be available if there's no tagged version.

**Comment by javiereguiluz** [comment] 2017-03-04 19:28
@iltar a bug fix has been proposed and if merged/deployed, this could be soon fixed. Thanks!

**Comment by javiereguiluz** [comment] 2017-03-07 09:58
Closing it as fixed because the http://symfony.com/doc/current/components/dotenv.html page now displays a proper error message with a link to the "master" doc:

![dotenv-doc](https://cloud.githubusercontent.com/assets/73419/23651182/fbaa1ac0-0324-11e7-904f-aa5549951f58.png)

**Closed by javiereguiluz** 2017-03-07 09:58 UTC
Labels: Bug, hasPR, Status: Reviewed, Website

**Comment by bitdagger** [comment] 2017-03-16 15:30
As a heads up, the documentation link in the [DotEnv Repo](https://github.com/symfony/dotenv) is currently set to https://symfony.com/doc/current/components/dotenv/index.html rather than the URL referenced in this issue, http://symfony.com/doc/current/components/dotenv.html  

While the link referenced here does point to the `master` URL, the link in the DotEnv repo is a generic 404 with no link to `master` (or anything else relevant).

**Comment by wouterj** [comment] 2017-03-16 15:32
@bitdagger thanks for reporting it. Can you maybe submit a PR to `symfony/symfony` to fix the link in the `README.md` file? The link should be updated to link to the correct one, `.../components/dotenv.html`
