### ISSUE TITLE
Documentation: a little bug in "Create your First Page in Symfony"

### ISSUE THREAD

**Issue by derowic** [symfony/symfony-docs#20087] opened 2024-08-01 09:10 UTC
http://localhost:8000/lucky/number 
may not work because of translations. It needs add country shortcut like in my case "/pl " before "/lucky/number"

example:
http://127.0.0.1:8000/pl/lucky/number

**Comment by xabbuh** [comment] 2024-08-01 09:55
Did you do more than what is described in the docs? Because I don’t see where anything related to translation should be present in your config according to the current state of the documentation.

**Comment by OskarStark** [comment] 2024-08-01 09:56
Can you maybe show your code in a reproducer repository?

**Comment by javiereguiluz** [comment] 2024-08-02 15:23
@derowic maybe you used the Symfony Demo app (https://github.com/symfony/demo/) as your base project and you added some new code to create the controllers according to docs?

Because the Symfony Demo app includes the locale in all its routes:

https://github.com/symfony/demo/blob/5dd64c8440b3a3b1133bd128babcf3cdf97f0ac1/config/routes.yaml#L17

That's why, if you create new controllers in that app, you need to add the locale to the URLs.

But, if you followed the code of the docs starting from a new Symfony app, then you don't have to add the locale to the URLs or deal with the locale or translation.

So, let's close this and if you have any other issues with this, please use the GitHub Discussions or Symfony Slack chat shown on https://symfony.com/support

Thanks!

**Closed as not planned by javiereguiluz** 2024-08-02 15:23 UTC
Labels: Waiting feedback
