### ISSUE TITLE
doc coding standard for shell

### ISSUE THREAD

**Issue by dbu** [symfony/symfony-docs#3826] opened 2014-05-03 11:25 UTC
i discussed this with @WouterJ on IRC and he proposed raising this as an issue here: i want to be able to copy-paste a list of command line operations from the doc into my shell. on linux it works perfectly fine to copy several lines of commands and paste them in one go. the symfony doc standards say to prepend every shell line with a `$` which prevents me from doing this. 

a good example is
http://symfony.com/doc/master/cmf/book/installation.html#set-up-the-database

could we relax on that rule and say that whole blocks of commands don't need the leading `$` unless there is also command output shown in the same example?

**Comment by javiereguiluz** [comment] 2016-12-06 11:29
I'm closing this as duplicate of #6865 where we are discussing about possible solutions. In fact, this will be fixed shortly on symfony.com. Here you can see how it will look: https://github.com/symfony/symfony-docs/issues/6865#issuecomment-265126846

Thank you all for the discussion.

**Closed by javiereguiluz** 2016-12-06 11:29 UTC
Labels: needs comments
