### ISSUE TITLE
Some block tags should not appear

### ISSUE THREAD

**Issue by chalasr** [symfony/symfony-docs#6839] opened 2016-08-03 14:11 UTC
[This chapter](https://symfony.com/doc/current/validation/custom_constraint.html#constraint-validators-with-dependencies) lets appear one `.. configuration-block::` tag that should not be displayed.

![](http://image.prntscr.com/image/6b412710fef147aab3137acce56ebef1.png)

I didn't open a PR simply because I can't figure how to fix it, as I didn't find any problem in [the corresponding file](https://github.com/symfony/symfony-docs/blob/master/validation/custom_constraint.rst) (line 163).

I guess the issue has been introduced in the same time as the new doc, but not sure.
If I find another one, I'll reference it here.

**Comment by wouterj** [comment] 2016-08-03 15:04
Thanks for reporting this @chalasr! The problem is the double colon (`::`) after the paragraph ("[...] validation system knows about it::").

As you deserve the credits for fixing this bug, can you maybe create a PR and change it to a single colon? (in reStructured Text, double colons indicate code blocks) Thanks!

**Comment by wouterj** [comment] 2016-08-03 15:05
Status: reviewed

**Comment by chalasr** [comment] 2016-08-04 08:20
See https://github.com/symfony/symfony-docs/pull/6833

**Comment by wouterj** [comment] 2016-08-04 15:32
Fixed now 🎉

**Closed by wouterj** 2016-08-04 15:32 UTC
Labels: Bug, Easy pick, Status: Reviewed
