### ISSUE TITLE
Link to deprecated feature

### ISSUE THREAD

**Issue by totaltrash** [symfony/symfony-docs#6781] opened 2016-07-29 09:58 UTC
Love the new documentation, well done all!

One minor thing i noticed, the 'next document' link at the bottom of the [Configuring Symfony (and Environments)](http://symfony.com/doc/current/configuration.html) page is [How to Use the Apache Router](http://symfony.com/doc/current/configuration/apache_router.html) which is deprecated and confusing for someone getting to the end of the 'Getting Started' section.

**Comment by javiereguiluz** [comment] 2016-08-29 13:50
@totaltrash thanks for this proposal. It makes a lot of sense!

The problem is that the "Learn More" section is generated automatically by our doc builder. We're going to update all of them manually to pick the articles and show them in the right order (and in different sections if there are a lot of articles).

This will take us a lot of time ... so for now, I've updated the article a bit in #6928 to clearly show that this is completely deprecated and should never be used. Thanks!

**Comment by javiereguiluz** [comment] 2017-04-15 17:38
Closing it as fixed by #6928 ... and the underlying issue will be fixed in the future when we reorganize docs. Thanks!

**Closed by javiereguiluz** 2017-04-15 17:38 UTC
Labels: hasPR
