### ISSUE TITLE
All code snippets are underlined

### ISSUE THREAD

**Issue by alexandre-daubois** [symfony/symfony-docs#20281] opened 2024-10-01 09:25 UTC
On macOS Sonoma 14.7 and Safari, I'm experiencing the following issue: all code snippets are underlined:

<img width="1512" alt="Capture d’écran 2024-10-01 à 11 24 09" src="https://github.com/user-attachments/assets/05b99060-c8e7-4c3d-a42e-331d9023b0ba">

The same goes for iPhone on iOS 18.0 and Safari:

<img width="300" alt="Capture d’écran 2024-10-01 à 11 24 09" src="https://github.com/user-attachments/assets/8e91b069-88e2-4c7a-9dbe-3a5be900e182">

**Comment by javiereguiluz** [comment] 2024-10-01 09:54
Alex, thanks a lot for the heads up. I'm sorry about this. This was caused by an indirect change done in another site section. It's fixed now. Thanks.

**Closed as completed by javiereguiluz** 2024-10-01 09:54 UTC
Labels: Website, bug
