### ISSUE TITLE
Better highlight selection for bash code blocks (copy and paste)

### ISSUE THREAD

**Issue by lakhman** [symfony/symfony-docs#6865] opened 2016-08-09 16:18 UTC
Currently when you double click on a bash code block, the $ is also selected.

By using the following jQuery snippet we can add a no-select to it to prevent it from being selected.

```
$(".highlight-bash pre span.nv:contains('$ ')").css('userSelect', 'none')
```

`:contains` seemed to suffice, maybe check if the element exactly contains the text to be 100% sure.

Could we add something like this to the symfony docs pages? It would make copy and paste that little bit easier. 😀  #lazy-programmer

![No selecting $ in bash](http://i.imgur.com/lCieote.gif)

This prevents the following when copy and pasting:

``` bash
> $ composer require friendsofsymfony/user-bundle "~2.0@dev"
bash: $: command not found

```

👍

**Comment by javiereguiluz** [comment] 2016-08-29 13:03
@lakhman I like this solution a lot. It's simple, it's clever and it works. Thanks!

I'm going to add it to symfony.com as soon as possible.

**Comment by javiereguiluz** [comment] 2016-08-29 13:27
It's not important ... but our highlighter seems to be doing some strange things. `.nv` is for "Name.Variable" elements. But the `$ ` should be highlighted as `.gp` for "Generic.Prompt".

In the Pygments website you can see the `.gp` in use for the Bash examples. But our Bash examples are wrongly considering that `$ ` is a bash script variable instead of the prompt.

**Comment by wouterj** [comment] 2016-08-29 15:11
Please note that this CSS solution is a problem: At least in Chrome, the text doesn't show up as selected, but is still included in the copied text. This means it'll still copy the middle `$` when selecting multi-line bash scripts, e.g:
```
$ symfony new blog
$ cd blog
```
This may result in some unexpected behaviour for our users.

@javiereguiluz I think that's because we're consistently using the wrong lexer for bash script. `bash` is for bash scripts, but `console` or `shell-session` is for console examples. These will be using the BashSessionLexer, which is meant for console examples.

**Comment by wouterj** [comment] 2016-08-29 15:20
Btw, if we're going to use `console` for all bash session examples and `$` has it's own class (`.gp`), there is a much nicer solution which works in *all* browsers without a problem:

```css
.gp{
  visibility:hidden;
  display:inline-block;
  width:16px; /* to be modified to be the width of "$ " */
}
.gp:before{
  content:'$ ';
  visibility:visible;
}
```

Example: http://jsbin.com/higohurepa/edit?html,css,output

Psuedo elements are never included in the copied text.

This will also finally close #3826

**Comment by javiereguiluz** [comment] 2016-08-29 15:29
@wouterj very nice!  The problem is that our highlighter is not doing the right highlight for `bash` blocks and I still don't know why :(

**Comment by wouterj** [comment] 2016-08-29 15:29
@javiereguiluz again, that's because we use `.. code-block:: bash`, but we have to use `.. code-block:: console`

**Comment by wouterj** [comment] 2016-08-29 15:41
see https://github.com/symfony/symfony-docs/pull/6930 for a PR fixing this

**Comment by xabbuh** [comment] 2016-09-21 19:28
Should be fixed now. Let's see how it looks like when the documentation has been rebuilt.

**Comment by wouterj** [comment] 2016-11-09 11:16
Reopening as https://github.com/symfony/symfony-docs/issues/6865#issuecomment-243156313 is not yet applied to symfony.com (and the issue was actually about that).

/cc @javiereguiluz

**Comment by javiereguiluz** [comment] 2016-11-09 11:28
@wouterj you are right. About the specific solution, how could we remove the `.gp` contents from the selection? This couldn't work because the `.gp` is not always `$` (for example for Windows commands):

```css
.gp{
  visibility:hidden;
  display:inline-block;
  width:16px; /* to be modified to be the width of "$ " */
}
.gp:before{
  content:'$ ';
  visibility:visible;
}
```

**Comment by wouterj** [comment] 2016-11-09 12:42
@javiereguiluz we can do something like this:

```css
.gp{
  visibility:hidden;
  display:inline-block;
  position:relative;
}
.gp:before{
  content:attr(data-value);
  position:absolute;
  visibility:visible;
}
```
```javascript
var gps = document.querySelectorAll('.gp');
[].forEach.call(gps, function (gp) {
  gp.dataset.value = gp.textContent;
});
```

See http://jsbin.com/nemufiwoho/1/edit?html,css,js,output (click the "run with js" button)

**Comment by javiereguiluz** [comment] 2016-12-06 11:27
@wouterj sorry for being late. I tested your code and it works as expected. I extended it to also unselect comments inside code blocks, as you suggested.

For short console blocks, you can now double-click and copy+paste+execute it:

![copy-simple](https://cloud.githubusercontent.com/assets/73419/20923946/30c78264-bbaf-11e6-865a-f28b09afd522.gif)

For long console blocks, this is how it looks:

#### Before

![copy-complex-before](https://cloud.githubusercontent.com/assets/73419/20923954/3d08db68-bbaf-11e6-847d-ac9a7546c814.gif)

#### After

![copy-complex-after](https://cloud.githubusercontent.com/assets/73419/20923956/3ff78414-bbaf-11e6-8d44-0a75a5fd319c.gif)

---

Hopefully this will be deployed on symfony.com anytime soon. Thanks!

**Comment by javiereguiluz** [comment] 2016-12-06 14:50
The fix has been deployed. You can test it for example here: http://symfony.com/doc/current/setup.html

Closing this as fixed. Thank you all ... specially Wouter for his invaluable help!

**Closed by javiereguiluz** 2016-12-06 14:50 UTC
Labels: hasPR, Website
