### ISSUE TITLE
(Un)setting pre-defined services is now deprecated

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#7464] opened 2017-02-12 19:38 UTC
See https://github.com/symfony/symfony/pull/21533

By the way, the "pre-defined services" name could be improved. I don't know what does it mean exactly.

**Comment by iltar** [comment] 2017-03-23 12:00
Some info if someone feels like writing docs about this issue:

I've done some digging and the name is correct, however, something like `compiled service` would also be possible. For those who are not familiar with it: This PR makes it impossible to change a pre-defined service. A predefined service, is a service that is registered in the `methodMap` property in the container. This is a key value array where the key is the service id, and the value is the method in the container to return that service.

Example:
```php
class SomeContainer extends Container
{
    private $methodMap = [
        'foo.baz' => 'getFoo_BazService',
    ];

    protected function getFoo_BazService()
    {
        return new FooBaz();
    }
    // ...
}

When calling `$container->set('foo.baz', ...);`, it will now register that service instance internally: `$this->services[$id] = $service;`. If I understand this PR correctly, 4.0 will no longer make this possible if this service is pre-defined (aka, available in the compiled/extended container).

Correct me if I'm wrong! /cc @nicolas-grekas

**Comment by nicolas-grekas** [comment] 2017-09-28 13:22
Duplicate of #8203 (or the other way around?)

**Comment by xabbuh** [comment] 2017-09-28 13:36
closing here in favour of #8203 (the other issue seems to contain more information for someone who wants to work on this)

**Closed by xabbuh** 2017-09-28 13:36 UTC
Labels: DependencyInjection, Missing Documentation
