### ISSUE TITLE
[RFC] [How to reproduce] issue/bug reproducer

### ISSUE THREAD

**Issue by noniagriconomie** [symfony/symfony-docs#11061] opened 2019-02-27 15:27 UTC
Hello!

Browsing issues in the main Symfony at https://github.com/symfony/symfony/issues
I have seen many times that a reproducers is welcome/required to reproduce locally/understand the issue mentionned

I think that with Symfony flex, it could be veery usefull to document a "how to reproducer" for issue purpose

That way, this doc (or url) could be put in the issue template, allowing developers to read it and provide a project having the issue reproduced in it

wdyt?

thank you

**Comment by javiereguiluz** [comment] 2019-02-27 15:51
Not sure I understand the proposal. We already have an article called:

[Creating a Bug Reproducer](https://symfony.com/doc/current/contributing/code/reproducer.html)

**Comment by noniagriconomie** [comment] 2019-02-27 16:14
@javiereguiluz ok, but what about writing it into https://github.com/symfony/symfony/blob/master/.github/ISSUE_TEMPLATE/1_Bug_report.md for example?

**Comment by javiereguiluz** [comment] 2019-04-15 14:07
I'm closing this as fixed because the issue template now includes a link to that article. Thanks!

![image](https://user-images.githubusercontent.com/73419/56139108-7b4fb600-5f98-11e9-9f86-0e5869672961.png)

**Closed by javiereguiluz** 2019-04-15 14:07 UTC
