### ISSUE TITLE
[Validator] Incorrect documentation

### ISSUE THREAD

**Issue by aybbou** [symfony/symfony-docs#6159] opened 2016-01-18 20:45 UTC
Hi,

So I was looking at the documentation for validating objects, and I read [here](http://symfony.com/doc/current/book/validation.html#validation-groups) that :

> If you have inheritance (e.g. User extends BaseUser) and you validate with the class name of the subclass (i.e. User), then all constraints in the User and BaseUser will be validated. However, if you validate using the base class (i.e. BaseUser), then only the default constraints in the BaseUser class will be validated.

But when I tested this, it wasn't working :

``` php
class BaseUser
{
    /**
     * @Assert\NotBlank()
     */
    public $name;
}
```

and

``` php
class User extends BaseUser
{
    /**
     * @Assert\NotBlank()
     */
    public $email;
}
```

and then in the controller I do something like :

``` php
    $user = new User();
    $errors = $this->get('validator')->validate($user, null, array('User'));
    dump($errors);
```

I have a `ConstraintViolationList` object containing only the `$email` violation. So I was wondering if this is a bug in the Validator component or the documentation is not up to date.

I am using Symfony 3.0.1 & PHP 5.6

Thanks.

**Comment by WouterJ** [comment] 2016-01-20 13:12
I can confirm the behaviour you described.

The JSR 303 specs (which the Validator component implements) describes the documented behaviour: http://beanvalidation.org/1.0/spec/#d0e1425 So it seems like the code should be changed to reflect this.

**Comment by WouterJ** [comment] 2016-02-06 23:18
Actually, I misread the specs and the docs should be fixed instead:

 > For every class X:
 >
 >  A. For each superclass Y of X, the group Y contains all constraints of the group Y of Y
 >    *this rule prepares formal concepts for recursive discovery*

So we should fix the docs instead. Can you maybe do that by clicking on the "edit" button of this particular page? (if you aren't sure or don't have time, feel free to say so and someone else will have a go on this).

**Comment by aybbou** [comment] 2016-02-09 21:04
Thank you for response @WouterJ, but I'm not sure that I fully understand what to do here.

In my previous example, should the `dump($errors)` only show the `$email` error ?

Also, I think that the B.III should be applied here:

> B. The group X contains the following constraints:
      III. if X has a direct superclass Y, every constraint in the group Y
      _all Default constraints hosted on the superclasses of X: constraints are inherited by the class hierarchy_

So I do think that the documentation is correct and the code should be changed.

/cc @webmozart

**Comment by WouterJ** [comment] 2016-05-21 10:31
Hmm, I think you're correct @aybbou. I think I confused "superclass" with "subclass".

Can you please open an issue in the code repository? (or even fix it in the code?)

**Comment by mickaelandrieu** [comment] 2016-06-26 20:19
@WouterJ to me sounds good regarding the explanation about Sequence group in docs http://symfony.com/doc/current/book/validation.html#group-sequence

nldr: if you set User as third argument, only validations from this class will be used.  The best here is to not fill the third argument, isn't it? 

Mickaël

**Comment by javiereguiluz** [comment] 2017-07-05 08:16
I'm closing this because the conclusion was that docs are correct and this is a bug in the code. Thanks!

**Closed by javiereguiluz** 2017-07-05 08:16 UTC
Labels: Bug, Validator
