### ISSUE TITLE
Proposed fix to avoid hide of anchor links behind sticky menu

### ISSUE THREAD

**Issue by alexander-schranz** [symfony/symfony-docs#15432] opened 2021-06-11 17:46 UTC
When I'm link for example to: https://symfony.com/doc/current/reference/forms/types/form.html#inherit-data

The `#inherit-data` headline is hidden between the sticky header.

By adding the following to the `CSS` should avoid this problem :

```css
html {
    scroll-padding-top: 90px;
}
```

**Comment by javiereguiluz** [comment] 2021-06-12 11:02
This is much more tricky than it sounds. I've spent several hours during the past months trying to fix this with `scroll-padding-top` (and other related CSS; because that doesn't work on Safari). Sadly I cannot make it work in all cases: all main browsers, all different device size breakpoints, all different page loading (normal page load, URL with anchor link page load, etc.)

That's why we decided to keep the JS library that we use to handle the scroll (https://www.npmjs.com/package/smooth-scroll). In my own experience, it works in all cases ... but some temporary glitch might have prevented to work for you. Maybe it's a bug in the library? Maybe it's a temporary random issue?

If you provide the steps to reproduce the bug reliably, we'll take a look. Thanks!

**Comment by alexander-schranz** [comment] 2021-06-12 11:14
@javiereguiluz oh I see. It scrolls directly to it when visit. That seems to work, I sometimes just used to click into the UrlBar and just type enter to get back to the headline.
Would it hurt to have both the `scroll-padding-top: 90px;` (on desktop / mobile seems have no sticky header) and keep the smooth scroll?

**Comment by alexander-schranz** [comment] 2021-06-15 14:55
@javiereguiluz  a case which I think is more used is when you click in the table of contents it seems not to use the `smooth-scroll`. E.g.: https://symfony.com/doc/current/reference/forms/types/form.html click on `action`.

**Comment by javiereguiluz** [comment] 2021-11-18 16:07
I'm closing this one as "fixed" because the new website design doesn't include any sticky header ... so this problem disappears. The entire docs section has been updated, so most of the people will never suffer this problem. Thanks!

**Closed as completed by javiereguiluz** 2021-11-18 16:07 UTC
Labels: Website
