### ISSUE TITLE
The documentation for the type option in collections should not advocate passing an instance

### ISSUE THREAD

**Issue by stof** [symfony/symfony-docs#4146] opened 2014-08-18 21:03 UTC
This is in http://symfony.com/doc/current/reference/forms/types/collection.html#type

Passing an instance rather the name of a registered type is very bad for performances.

**Comment by WouterJ** [comment] 2015-05-01 17:59
Closing as duplicate of #3443

**Closed by WouterJ** 2015-05-01 17:59 UTC
