### ISSUE TITLE
 Symfony 4: No route found for "GET /" just after installation

### ISSUE THREAD

**Issue by zer0uno** [symfony/symfony-docs#9178] opened 2018-01-31 00:21 UTC
I'm starting out with Symfony 4 following this guide https://symfony.com/doc/current/setup.html, so I have executed one after the other these commands:

1. `composer create-project symfony/website-skeleton my-project`
2. `cd my-project`
3. `composer require server --dev`
4. `php bin/console server:run`

but when I browse to `http://localhost:8000` I get a `No route found for "GET /"` error.

**Comment by javiereguiluz** [comment] 2018-01-31 17:07
I can reproduce this bug with the given steps. Now let's find the cause of it and fix it. Thanks!

**Comment by javiereguiluz** [comment] 2018-02-01 08:01
I've just debug the error. The problem is that this code in `PhpMatcherDumper.php` never gets executed because `$code` is not empty:

```php
        if ('' === $code) {
            $code .= "        if ('/' === \$pathinfo) {\n";
            $code .= "            throw new Symfony\Component\Routing\Exception\NoConfigurationException();\n";
            $code .= "        }\n";
        }
```

In my case, the `$code` variable contained:

```
PhpMatcherDumper.php on line 157:
"""
        if (0 === strpos($pathinfo, '/_')) {\n
            // _twig_error_test\n
            if (0 === strpos($pathinfo, '/_error') && preg_match('#^/_error/(?P<code>\\d+)(?:\\.(?P<_format>[^/]++))?$#s', $pathinfo, $matches)) {\n
                return $this->mergeDefaults(array_replace($matches, array('_route' => '_twig_error_test')), array (  '_controller' => 'twig.controller.preview_e ▶
            }\n
\n
            // _wdt\n
            if (0 === strpos($pathinfo, '/_wdt') && preg_match('#^/_wdt/(?P<token>[^/]++)$#s', $pathinfo, $matches)) {\n
                return $this->mergeDefaults(array_replace($matches, array('_route' => '_wdt')), array (  '_controller' => 'web_profiler.controller.profiler:tool ▶
            }\n
\n
            if (0 === strpos($pathinfo, '/_profiler')) {\n
                // _profiler_home\n
                if ('/_profiler' === $trimmedPathinfo) {\n
                    $ret = array (  '_controller' => 'web_profiler.controller.profiler:homeAction',  '_route' => '_profiler_home',);\n
                    if (substr($pathinfo, -1) !== '/') {\n
                        return array_replace($ret, $this->redirect($rawPathinfo.'/', '_profiler_home'));\n
                    }\n
\n
                    return $ret;\n
                }\n
\n
                if (0 === strpos($pathinfo, '/_profiler/search')) {\n
                    // _profiler_search\n
                    if ('/_profiler/search' === $pathinfo) {\n
                        return array (  '_controller' => 'web_profiler.controller.profiler:searchAction',  '_route' => '_profiler_search',);\n
                    }\n
\n
                    // _profiler_search_bar\n
                    if ('/_profiler/search_bar' === $pathinfo) {\n
                        return array (  '_controller' => 'web_profiler.controller.profiler:searchBarAction',  '_route' => '_profiler_search_bar',);\n
                    }\n
\n
                }\n
\n
                // _profiler_phpinfo\n
                if ('/_profiler/phpinfo' === $pathinfo) {\n
                    return array (  '_controller' => 'web_profiler.controller.profiler:phpinfoAction',  '_route' => '_profiler_phpinfo',);\n
                }\n
\n
                // _profiler_search_results\n
                if (preg_match('#^/_profiler/(?P<token>[^/]++)/search/results$#s', $pathinfo, $matches)) {\n
                    return $this->mergeDefaults(array_replace($matches, array('_route' => '_profiler_search_results')), array (  '_controller' => 'web_profiler. ▶
                }\n
\n
                // _profiler_open_file\n
                if ('/_profiler/open' === $pathinfo) {\n
                    return array (  '_controller' => 'web_profiler.controller.profiler:openAction',  '_route' => '_profiler_open_file',);\n
                }\n
\n
                // _profiler\n
                if (preg_match('#^/_profiler/(?P<token>[^/]++)$#s', $pathinfo, $matches)) {\n
                    return $this->mergeDefaults(array_replace($matches, array('_route' => '_profiler')), array (  '_controller' => 'web_profiler.controller.prof ▶
                }\n
\n
                // _profiler_router\n
                if (preg_match('#^/_profiler/(?P<token>[^/]++)/router$#s', $pathinfo, $matches)) {\n
                    return $this->mergeDefaults(array_replace($matches, array('_route' => '_profiler_router')), array (  '_controller' => 'web_profiler.controll ▶
                }\n
\n
                // _profiler_exception\n
                if (preg_match('#^/_profiler/(?P<token>[^/]++)/exception$#s', $pathinfo, $matches)) {\n
                    return $this->mergeDefaults(array_replace($matches, array('_route' => '_profiler_exception')), array (  '_controller' => 'web_profiler.contr ▶
                }\n
\n
                // _profiler_exception_css\n
                if (preg_match('#^/_profiler/(?P<token>[^/]++)/exception\\.css$#s', $pathinfo, $matches)) {\n
                    return $this->mergeDefaults(array_replace($matches, array('_route' => '_profiler_exception_css')), array (  '_controller' => 'web_profiler.c ▶
                }\n
\n
            }\n
\n
        }\n
\n
"""
```

Maybe @yceruto, who created that code, can help us solve this problem. Thanks!

**Comment by yceruto** [comment] 2018-02-01 13:44
Sadly, the trick (upon installation) only works if there is no package that adds a route to the application, and that's the case for `symfony/website-skeleton` & its dev-requirements: [`symfony/profiler-pack`](https://github.com/symfony/website-skeleton/blob/4.0/composer.json#L35) -> [`symfony/web-profiler-bundle`](https://github.com/symfony/profiler-pack/blob/master/composer.json#L10)

See recipe for [`symfony/web-profiler-bundle`](https://github.com/symfony/recipes/blob/master/symfony/web-profiler-bundle/3.3/config/routes/dev/web_profiler.yaml), same if [`symfony/twig-bundle`](https://github.com/symfony/recipes/blob/master/symfony/twig-bundle/3.3/config/routes/dev/twig.yaml) was installed by transitivity.

**Comment by javiereguiluz** [comment] 2018-02-01 14:02
Just thinking out loud: could we detect somehow in the dumper if there's any route associated with the `/` path and if there's none, add it like in the previous trick? Thanks!

**Comment by javiereguiluz** [comment] 2018-02-01 16:36
@yceruto this super quick and dirty code solves the problem:

```php
$homepageIsDefined = false;
foreach ($collection as $dumperRoute) {
    if ('/' === $dumperRoute->getRoute()->getPath()) {
        $homepageIsDefined = true;
        break;
    }
}

if (!$homepageIsDefined) {
    $code .= "        if ('/' === \$pathinfo) {\n";
    $code .= "            throw new Symfony\Component\Routing\Exception\NoConfigurationException();\n";
    $code .= "        }\n";
}
```

**Comment by VladimirShaganian** [comment] 2018-02-02 21:36
Same problem.

**Comment by javiereguiluz** [comment] 2018-02-04 16:40
@yceruto I've proposed a simpler solution in https://github.com/symfony/symfony/pull/26041 Hopefully it will fix this issue.

**Comment by javiereguiluz** [comment] 2018-02-05 07:51
I'm closing this issue because we are working on it on the code repository, which is where this can be fixed. Thanks!

**Closed by javiereguiluz** 2018-02-05 07:51 UTC
Labels: Bug, Status: Reviewed, hasPR

**Comment by JanuszWitrykus** [comment] 2018-03-07 17:31
This is not fair. Lost time.

**Comment by zacpattersondc** [comment] 2018-03-16 19:09
I had the same issue. I fixed it by creating a controller and modifying the routes.yami file. This video shows the solution at around 11:30 https://www.youtube.com/watch?v=t5ZedKnWX9E

**Comment by RallyCongressStaff** [comment] 2018-03-19 20:46
This is still a bug, the issue shouldn't be closed.

**Comment by yceruto** [comment] 2018-03-19 21:07
I'm not sure to understand the downvotes on [this comment](https://github.com/symfony/symfony-docs/issues/9178#issuecomment-363006113), [the fix was merged](https://github.com/symfony/symfony/pull/26041) and will be out in the next release, so this documentation will be fine.

**Comment by Schrodinger0** [comment] 2018-10-10 10:04
same problem .. anything useful here ?

**Comment by xabbuh** [comment] 2018-10-10 10:07
@Schrodinger0 What do you mean with "same problem"?

**Comment by Schrodinger0** [comment] 2018-10-10 10:16
just after Installation 
![image](https://user-images.githubusercontent.com/41432226/46729667-e9c85a00-cc7d-11e8-9c55-5bcf1fd7d240.png)

**Comment by xabbuh** [comment] 2018-10-10 10:46
That's expected, a new application has no default route. But there should be a nice page nonetheless displaying some information. And you can then continue creating your first page as described at https://symfony.com/doc/current/page_creation.html.
