### ISSUE TITLE
DoctrineCacheBundle

### ISSUE THREAD

**Issue by EmanueleMinotto** [symfony/symfony-docs#4940] opened 2015-01-29 23:14 UTC
Since the version 1.3.0 of DoctrineBundle, the DoctrineCacheBundle is included by default, should it be included in the symfony.com documentation (Bundles section I think)?

**Comment by javiereguiluz** [comment] 2015-01-30 07:18
@EmanueleMinotto the problem is that right now DoctrineCacheBundle doesn't have a real documentation, just a long `README.md` file. In order to integrate it in symfony.com, we need something like this https://github.com/doctrine/DoctrineFixturesBundle/tree/master/Resources/doc or this https://github.com/doctrine/DoctrineBundle/tree/master/Resources/doc

**Comment by EmanueleMinotto** [comment] 2015-03-15 19:32
@javiereguiluz is it enough? https://github.com/doctrine/DoctrineCacheBundle/blob/master/Resources/doc/index.rst

**Comment by javiereguiluz** [comment] 2015-03-15 19:33
@EmanueleMinotto that's perfect! Thank you very much for working on this.

**Comment by WouterJ** [comment] 2015-05-08 09:06
@javiereguiluz is there a plan to add the docs to the "Bundles related to Doctrine project" section of the 3rd party bundle doc?

**Comment by xabbuh** [comment] 2015-06-02 20:54
ping @javiereguiluz

**Comment by EmanueleMinotto** [comment] 2015-09-20 15:16
Any news about this?

**Comment by javiereguiluz** [comment] 2015-09-23 13:31
Thanks for pinging me about this. I can't promise a date, but this will be done "soon".

**Comment by javiereguiluz** [comment] 2016-01-04 09:26
I haven't forget about this issue. I'm just waiting for the documentation to be updated to RST format (see https://github.com/doctrine/DoctrineCacheBundle/pull/78)

**Comment by javiereguiluz** [comment] 2016-02-26 11:15
We can close this issue as "fixed". The doc for doctrineCacheBundle is now published at: http://symfony.com/doc/master/bundles/DoctrineCacheBundle/index.html

**Closed** 2016-02-26 11:28 UTC
Labels: Website
