### ISSUE TITLE
Documentation Invalid for Testing Host Matched Routes

### ISSUE THREAD

**Issue by tomchkk** [symfony/symfony-docs#6421] opened 2016-04-01 09:54 UTC
The section [Testing your Controllers](http://symfony.com/doc/2.8/components/routing/hostname_pattern.html#testing-your-controllers) in the **How to Match a Route Based on the Host** document no longer appears to be valid from Symfony 2.8.

The documentation indicates to set the Host HTTP header on the request:

```
$crawler = $client->request(
    'GET',
    '/homepage',
    array(),
    array(),
    array('HTTP_HOST' => 'm.' . $client->getContainer()->getParameter('domain'))
);
```

After recently updating my application from 2.7 to 2.8, I found that this technique no longer works, and seems to have been invalided by the fix for issue [#15398](https://github.com/symfony/symfony/issues/15398).

As per the amended test class `src/Symfony/Component/BrowserKit/Tests/ClientTest.php` the correct method now appears to be to provide the full uri to the `$client->request()` method.

The updated test request might instead look like this:

```
$uri = 'm.' . $client->getContainer()->getParameter('domain')) . '/homepage';
$crawler = $client->request('GET', $uri);
```

**Comment by javiereguiluz** [comment] 2019-01-21 15:03
I tested this in the [Symfony Demo app](https://github.com/symfony/demo) and I can't reproduce it. I changed the `testPublicUrls()` as follows:

```diff
-$client->request('GET', $url);
+$client->request('GET', $url, [], [], ['HTTP_HOST' => 'example.com']);
```

All test passed correctly. Then I changed one of the public URLs as follows:

```diff
-@Route("/", defaults={"page": "1", "_format"="html"}, methods={"GET"}, name="blog_index")
+@Route("/", defaults={"page": "1", "_format"="html"}, methods={"GET"}, name="blog_index", host="acme.com")
```

And one test failed, as expected. Then I changed `acme.com` by `example.com` in the route definition and all tests passed again. So I think this is working as expected (at least in Symfony 4.x versions) and that's why I'm closing it.

If you think my review is wrong, please fork the Symfony Demo app and create a small test which reproduces the bug so we can investigate it. Thanks!

**Closed by javiereguiluz** 2019-01-21 15:03 UTC
Labels: Actionable, Bug, Testing
