### ISSUE TITLE
Messed doc structure / broken navigation logics

### ISSUE THREAD

**Issue by Arkemlar** [symfony/symfony-docs#6965] opened 2016-09-13 17:51 UTC
New (relative to previous version) doc structure on symfony.com is messed up. Currently it is much worse than 2.3 version where Coobook, Components, The Symfony Book - everethyng separated and have strict and intuitive structure.
1. The current version messed up structure on old Cookbook, The Symfony Book and Components topics in Learn More section, harder to search in that messy list of different things. Whenever I remember the old strucure it helps me a lot, otherwise I need to waste more time to find what I searching for.
2. Topics have bad navigation menu - you need to go to the root page (with Learn more list) to navigate over topics inside new Components section. Actually, the Components section in left menu not even expandable like Getting Started or Guides sections.
3. Topics have different URI path structure (inherited from old navigation principles).
4. Sometimes (rarely) breadcrumbs showing weird things with like 6-7 jumps instead of normal 3-4. (Id like to post a link on such a page but forgot what a page it was and failed in search attempts).

Please do something with that. May be come back to old structure or fix 1 and 2 (most annoying) things.

**Comment by javiereguiluz** [comment] 2016-09-14 19:28
@Arkemlar currently there are some issues in the navigation of the docs. The reason is the way we added links to related articles, that messes the navigation TOCs (and breaks PDFs too for example).

The problem is that this is pretty hard to solve and the main Doc maintainers are at the moment very busy, so we'll need to wait still a bit more. Thanks for your patience.

**Comment by Arkemlar** [comment] 2016-10-14 16:05
Here is example of 4-th number (breadcrumb bug).
https://symfony.com/doc/current/configuration/environments.html

**Comment by Arkemlar** [comment] 2017-01-06 20:17
@javiereguiluz I feel like I need to notice community about another big mess - in api.symfony.com.
Just look at [this ](http://api.symfony.com/3.2/Symfony/Component/Security/Guard/GuardAuthenticatorInterface.html) link.
Now try to find this namespace (\Symfony\Component\Security\Guard\GuardAuthenticatorInterface) in index menu (left side tree). You won't!!
But it is not all yet. Try to click on Guard [link ](http://api.symfony.com/3.2/Symfony/Component/Security/Guard.html) in top breadcrumbs menu. It leads to page with /3.2/ piece in url, BUT in top right corner of the page in select box you will see that "2.8 branch" is selected.
I feel really fooled with that api doc site. Previously I never detected such behavior.
I realize that this topic might be not right place to report that, but I don't know who is responsible for API doc part of documentation. Please transfer this to right person or tell me where to post this report.

**Comment by xabbuh** [comment] 2017-01-08 12:48
What do you mean with the left menu? For me, the page you linked to looks like this:

<img width="1280" alt="bildschirmfoto 2017-01-08 um 13 45 17" src="https://cloud.githubusercontent.com/assets/1957048/21749885/c0a2cbf6-d5a8-11e6-9cf1-b210a66b99d7.png">

As you can see, the linked interface is highlighted in the menu tree.

> But it is not all yet. Try to click on Guard link in top breadcrumbs menu. It leads to page with /3.2/ piece in url, BUT in top right corner of the page in select box you will see that "2.8 branch" is selected.

I can confirm that. And by the way, the version highlighted when following your link is 3.1 which is confusing too as the link should open the 3.2 docs.

**Comment by Arkemlar** [comment] 2017-01-09 21:35
@xabbuh my picture is different:
![default](https://cloud.githubusercontent.com/assets/19671202/21784265/c8384eda-d6cb-11e6-9af9-bdcc6f404036.png)
there are no Guard namespace in left side.. (I used the first link provided in my post). By default it is collapsed so I opened the relevant tree leaf for proof.
Also note that in your screenshot there is no ACL leaf, but in my screenshot it is.

> I can confirm that. And by the way, the version highlighted when following your link is 3.1 which is confusing too as the link should open the 3.2 docs.

It is true, I see the same.

**Comment by javiereguiluz** [comment] 2017-02-14 16:41
I'm closing this as "fixed":

* We can't change the navigation based on topics ... so that's a won't fix.
* Sometimes breadcrumbs are wrong (it's reported in #7418 too) ... this has been fixed and it'll be online after the merge and deploy process.
* About the API ... it's probably a bug in Sami (https://github.com/FriendsOfPHP/Sami)  which is the application used to generate the API docs. So please, report the issue in that repository. Thanks!

**Closed by javiereguiluz** 2017-02-14 16:41 UTC
