### ISSUE TITLE
[Book] Step 9 Issue: Cannot create new Comment

### ISSUE THREAD

**Issue by roo7cause** [symfony/symfony-docs#15252] opened 2021-04-16 20:58 UTC
Hello Symfony Community,

I am reading the book about Symfony 5: The Fast Track and I spotted a potential Bug in the book, where the content suggest that at the specific moment something is possible to do, but it actually is not. 

**DETAILS:**
This chapter: https://symfony.com/doc/current/the-fast-track/en/9-backend.html
just before 9.2 chapter suggests that it is possible to create a New Comment in Admin dashboards. However, I receive the following error:
![image](https://user-images.githubusercontent.com/10271265/115082683-94342e80-9f06-11eb-85cc-8bc4e7cddca3.png)

This errors tells me that the `conference_id ` is `null`. This is true, because at this very step, we do not have an option to choose to which Conference we want to add a new comment. Yet on the Book's screenshots it looks like it is possible. Now, I am just begining to learn about Backend development, so if this should be somehow 'auto-filled', please let me know what am I missing (I cannot imagine how it can be auto-filled, if I have multiple Conferences defined.. how would it automatically know into which Conference to put the comment to?).

We have 2 Entities: Conference and Comment, where the relationship is OneToMany (Conference -> Comment). This is all generated with ORM and 'make:entity' package. So there is not a lot of code to actually modify by this step, thus I believe there might be a bug either in the book itself (perhaps some missing step?) or with the composer packages that we used in Book.

PS: I am aware I am writting this in Symfony-docs, but in the Book's repository, there is no option to create an Issue. Please move this issue if this is not correct repository or suggest me an URL where to open it.

**Comment by cybd** [comment] 2021-05-02 21:27
You should put
```
        $fields = parent::configureFields($pageName);
        $fields[] = AssociationField::new('conference');
        return $fields;
```
in configureFields method of CommentCrudController file.
AssociationField was forgotten at this step. It's a good chance to check and fix yourself.

**Comment by shoshinmas** [comment] 2021-06-05 21:25
This helps a lot, thank you!

**Comment by GrossmanPro** [comment] 2022-03-18 23:06
Ran into the same issue.  On the **Setting up an Admin Backend** page of the online version of the book, the "Add some comments without photos..." section and screen shot should come after the **Customizing EasyAdmin** section.

**Comment by mariojackson** [comment] 2022-03-25 19:03
I just ran into the same problem.

**Comment by haxworx** [comment] 2022-04-14 15:12
Again, running into the same problem.

**Comment by haxworx** [comment] 2022-04-14 15:46
As noticed by @GrossmanPro the ordering of the book is incorrect. After Customizing the EasyAdmin section I was successfully able to add comments via the Admin backend.

**Comment by bruteforks** [comment] 2022-11-27 02:36
same problem. Also need to add `use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;` with cybd's fix

**Comment by BigBenJr** [comment] 2023-03-17 06:56
I got the same issue reading "The Fast Track" for Symfony 6.2, it's still not fixed.

**Comment by alamirault** [comment] 2023-07-29 20:43
Updating Fast Track is mandatory

Friendly ping @fabpot, as I think we can do nothing in our side (and many people have the problem) ?

**Comment by javiereguiluz** [comment] 2023-09-08 09:52
I can confirm this error. You can't create a new `Comment` at that point.

So, I'm proposing some changes in the Fast Track private repository to move this section a bit below, after the `Comment` entity is configured explicitly.

**Comment by alamirault** [comment] 2023-09-27 21:49
I now see `AssociationField::new('conference');` on https://symfony.com/doc/current/the-fast-track/en/9-backend.html#customizing-easyadmin

So I think your PR has been merged @javiereguiluz  ?

**Comment by javiereguiluz** [comment] 2023-09-28 06:30
No. Sadly it hasn't been merged yet. It's about changing the order of some contents.

**Comment by Yumekawa-chan** [comment] 2023-10-24 08:13
I just ran into the same problem.

**Comment by javiereguiluz** [comment] 2024-01-26 15:22
I'm closing this one as "fixed" ... because the fix for this issue was merged in the private repository that contains the book contents. The fix has not been published in production yet ... but the next book version will contain the fix.

Thanks!

**Closed as completed by javiereguiluz** 2024-01-26 15:22 UTC
