### ISSUE TITLE
Add documentation to build a REST API with Symfony

### ISSUE THREAD

**Issue by michaelperrin** [symfony/symfony-docs#6780] opened 2016-07-29 08:49 UTC
Following the "Project Mercury" release and [my comment about it](http://symfony.com/blog/introducing-the-new-symfony-documentation#comment-20654) (congrats by the way!), @javiereguiluz proposed to open issues about topics that could be tackled in the Symfony documentation.

With the rise of APIs and service-oriented architecture, it would be great to have a starting point on how to build REST APIs with Symfony and some third-party bundles making it easier.
The current documentation is still very MVC-centric, although consuming APIs with JavaScript frameworks(for instance) gets very common. There are many tutorials and many ways to build REST APIs, but I think that newcomers would be glad to find such a starting point.

A step-by-step example would be appropriate, with an API built upon a simple entity (with a least one relation), with the main operations (create, update, delete, show, search) being impletend. The following subjects could be mentioned:
- Quick reminder of HTTP verbs
- HATEOAS
- API documentation (NelmioApiBundle / Swagger)

Should the API be built with [Dunglas Core Api Bundle](https://github.com/api-platform/core) or [FOSRestBundle](https://github.com/FriendsOfSymfony/FOSRestBundle)? I like the pragmatic approach of Dunglas Bundle and the strong focus on standards, but I have no experience with it yet, and it may be out of the scope of the main Symfony documentation.

We should either way choose one very pragmatic approach, so that users don't get confused and overwhelmed by the many possibilities. Other possibilities could however be mentioned.

This issue is of course open to discussion!

**Comment by javiereguiluz** [comment] 2017-03-07 09:30
This issue is more and more important every day. There's no modern article explaining how to create APIs with Symfony. Some people are using the Form component for this (!!!!!) (see https://github.com/symfony/symfony/issues/21895 and lots of comments on Symfony's Slack).

**Comment by javiereguiluz** [comment] 2017-03-07 09:38
I'm closing this as a duplicate of #5260 ... but I've copied your comment there to not lose it. Thanks!

**Closed by javiereguiluz** 2017-03-07 09:38 UTC

**Comment by michaelperrin** [comment] 2017-03-07 09:49
Thanks @javiereguiluz for bringing this up again!

The Symfony docs are really great, but focus a lot on the way we were making web pages when the docs were written. Nothing bad about it, as it is still appropriate in many cases, but that would be nice to show that Symfony is great for making APIs as well, and give new comers a "framework" (I don't mean a library, but a framework of how to do it) through the docs.

Maybe the docs could have some Cookbooks (even if the term is not used anymore) about such things people look for for their project. We may mention the creation of GraphQL APIs as well.

But let's continue the conversion in the other issue (#5260).
