### ISSUE TITLE
[Website] "New in version" overlap versionadded text

### ISSUE THREAD

**Issue by wkania** [symfony/symfony-docs#16082] opened 2021-11-08 18:10 UTC
[Firefox and Chromium](https://symfony.com/doc/5.2/validation.html#debugging-the-constraints)
![image](https://user-images.githubusercontent.com/57155526/140795226-9e675e02-6ebf-4abb-b514-3186d3895caf.png)

**Comment by noniagriconomie** [comment] 2021-11-08 18:22
Safari v15.0 as well has this

**Comment by javiereguiluz** [comment] 2021-11-09 21:12
This should have been fixed now. If you still see the issue in some specific pages, it's because of some caching, and it should be fixed in a few minutes. Thanks!

**Closed as completed by javiereguiluz** 2021-11-09 21:12 UTC
Labels: Website

**Comment by isleshocky77** [comment] 2021-12-08 16:37
@javiereguiluz I'm still seeing this on a new page I just went to and haven't visited before.

https://symfony.com/doc/4.1/routing/redirect_in_config.html

![weird-overlap](https://user-images.githubusercontent.com/361586/145247112-f90d7a41-a48c-4958-aecb-2b394b560d6c.png)

*NOTE* The example page for this ticket in the description _does_ show correctly. Is this something that had to be fixed everywehre?

**Comment by javiereguiluz** [comment] 2021-12-08 16:58
Thanks for reporting. I've rebuilt the docs for that outdated version ... and the problem is now fixed.
