### ISSUE TITLE
[Website][Minor] Symfony Releases description

### ISSUE THREAD

**Issue by 94noni** [symfony/symfony-docs#14348] opened 2020-10-05 19:07 UTC
On https://symfony.com/releases
According to this page and as of now, the `v5.2` status is `In development` but should be `In stabilization` 
Related to https://symfony.com/doc/current/contributing/community/releases.html#development

Can this page be updated? (not inside this repository)

Also, will it be possible to have in the `Symfony Releases Timeline`, like the [PHP](https://www.php.net/supported-versions.php) the date diff compared to now?
(related to https://github.com/symfony/symfony/pull/37754)

Thank you :)

**Comment by javiereguiluz** [comment] 2020-10-09 07:16
Thanks for these proposals ... however, we must close as "won't fix":

1) You are right about the "stabilization phase" ... but that's "an internal detail" of the general "in development" phrase. We prefer to keep the current description because we think it's easier to understand for visitors.

2) We wanted to do that ... but the problem is that Symfony releases, unlike PHP releases, don't have a defined date, so we cannot count down until that moment. We know that Symfony will release "at the end of" (May and November). But we never know the exact day (or time).

Thanks for understanding! ... and please, keep sending proposals!

**Closed as completed by javiereguiluz** 2020-10-09 07:16 UTC
Labels: Website
