### ISSUE TITLE
Search window displays twice on website

### ISSUE THREAD

**Issue by alexandre-daubois** [symfony/symfony-docs#19517] opened 2024-02-06 09:16 UTC
Hi 👋 

I was looking for something on the doc by pressing double shift and found out that the results are currently displayed twice:

![image](https://github.com/symfony/symfony-docs/assets/2144837/434cf212-f3a9-4ea8-8e5f-98151e867f4e)

On Safari, latest macOS version.

cc @javiereguiluz

**Comment by javiereguiluz** [comment] 2024-02-07 07:44
Sorry about this bug. It was caused by an unintended double import of Stimulus related to our recent migration to AssetMapper (https://symfony.com/blog/upgrading-symfony-websites-to-assetmapper).

It's fixed now. Thanks.

**Closed as completed by javiereguiluz** 2024-02-07 07:44 UTC
Labels: Website
