### ISSUE TITLE
Improving documentation for translation configuration

### ISSUE THREAD

**Issue by elfring** [symfony/symfony-docs#15132] opened 2021-03-19 14:30 UTC
[A system configuration file](https://symfony.com/doc/current/translation.html#configuration "Selection of translation parameters") is described in a terse way.
I am unsure if the published description is complete already.

[Translation contents can be extracted](https://symfony.com/doc/current/translation.html#extracting-translation-contents-and-updating-catalogs-automatically "Extracting translation contents and updating catalogs automatically") from source files.
I am looking also for guidance how the files will be selected so that translatable data will be stored there.
Which configuration parameters influence [the applied file format for message files](https://symfony.com/doc/current/translation.html#translation-resource-file-names-and-locations "Translation resource/file names and locations")?

**Comment by xabbuh** [comment] 2021-03-22 16:30
Can you please elaborate a bit? What information are you missing or where would you have liked to get more in-depth details?

**Comment by elfring** [comment] 2021-03-23 08:39
Another wording approach:
At which point in time will the files be chosen which should provide translated data?

**Comment by xabbuh** [comment] 2021-03-23 09:05
In the paragraph that you linked above there is this paragraph:

![Bildschirmfoto 2021-03-23 um 10 03 26](https://user-images.githubusercontent.com/1957048/112121118-2c1c5200-8bbf-11eb-821b-061e5862ad35.png)

Isn't that the information you are looking for?

**Comment by elfring** [comment] 2021-03-23 09:25
I got the impression that this information does not answer which of the supported translation file formats would actually be applied.

**Comment by elfring** [comment] 2021-03-23 14:10
I have marked a short text in the file “index.html.twig” [for translation](https://symfony.com/doc/current/translation.html#using-twig-tags "Using Twig tags") (as a simple test).
But the command “`php bin/console translation:update --force --xliff-version=2.1 de`” displays the information “`[WARNING] No translation messages were found.`” so far.

:thinking: Do I need to tell the software tool in more detail which directories should be taken into account for text extraction?

**Comment by xabbuh** [comment] 2021-03-23 14:34
If I change `--xliff-version=2.1` to `--xliff-version=2.0`, your example works for me in a freshly set up application.

**Comment by elfring** [comment] 2021-03-23 14:50
It seems that the version number does not change the data processing result for my test run.
The command parameters “`-vvv`” and “`--verbose`” do not trigger the display of additional information here.

**Comment by xabbuh** [comment] 2021-03-23 14:56
Can you please create a small application that allows to reproduce what you experience?

**Comment by elfring** [comment] 2021-03-23 14:58
How are the chances to determine which files would be taken into account for the desired text extraction?

**Comment by xabbuh** [comment] 2021-03-23 15:29
While debugging you can hook into the `TranslationUpdateCommand` and inspect which paths are passed to the extractor.

**Comment by elfring** [comment] 2021-03-24 08:00
:thinking: How do you think about to add any command options for the data export of paths according to analysed files?

**Comment by xabbuh** [comment] 2021-03-24 08:28
I think we could add some debug output to the command which would then display the inspected directories when run in the verbose mode. Would you like to give that a try or open a feature request in the code repository?

**Comment by elfring** [comment] 2021-03-24 09:54
Thanks for your constructive feedback.

>… open a feature request in the code repository?

Will the clarification be continued with a topic like “[Export analysis results according to the translation process](https://github.com/symfony/symfony/issues/40570 "Clarification request")”?

**Comment by elfring** [comment] 2021-03-24 12:02
>While debugging you can hook into the `TranslationUpdateCommand` and inspect which paths are passed to the extractor.

I have added the statement “`fwrite(STDERR, 'extract: ' . $path . PHP_EOL);`” before [the mentioned method call](https://github.com/symfony/symfony/blob/e53bb8b4f268c4b594d91f8cb8f0d22f01fe99fb/src/Symfony/Bundle/FrameworkBundle/Command/TranslationUpdateCommand.php#L194 "Checking text extraction") in the vendor directory.

Another test run displayed the following information.

```
extract: …/vendor/symfony/http-kernel/EventListener/LocaleAwareListener.php
extract: …/vendor/symfony/framework-bundle/Command/TranslationDebugCommand.php
extract: …/vendor/symfony/framework-bundle/CacheWarmer/TranslationsCacheWarmer.php
```


I find that a previous statement like “`$io->comment('Parsing templates...');`” can also trigger further software development considerations.
Which statements do take care of text extraction from PHP source files according to my evolving application?

Do I overlook any system configuration details?

**Comment by xabbuh** [comment] 2021-03-24 12:40
I have no idea what is going on in your application that the `templates` directory is not considered. But the documentation repository is not the best place to debug this.

If you need more help in debugging your application, I suggest to to use one of our [support channels](https://symfony.com/support). If you instead think that there is a bug in Symfony, please create a full example application that allows to reproduce your issue and open an issue in the code repository.

**Comment by elfring** [comment] 2021-03-24 12:55
>If you instead think that there is a bug in Symfony, …

I might get such an impression when the referenced source file “TranslationUpdateCommand.php” would be incomplete at the moment.
How many data extraction function calls would you expect so far?

My understanding of the discussed implementation details is also still evolving.


>… and open an issue in the code repository.

:crystal_ball: How are the chances that the clarification will become more helpful for issues which were registered already?

(Can any telephone calls help to achieve a better common understanding?)

**Comment by xabbuh** [comment] 2021-03-24 13:16
> How are the chances that the clarification will become more helpful for issues which were registered already?

This depends on the information that we get. Not being able to reproduce an issue means that we can hardly fix it. An example application is usually the best effort to move things forward.

**Comment by elfring** [comment] 2021-03-24 13:20
>An example application is usually the best effort to move things forward.

:thinking: Should the available Symfony source code be sufficient for the clarification of affected implementation details?

**Comment by xabbuh** [comment] 2021-03-24 13:35
Honestly I don't understand what you are asking for.

To summarize what has been said:

- If you think that there is a bug, please create a fully working example application that allows to do so and with that open an issue in the code repository.
- If you need support with getting your application running, please use any of the available [support channels](https://symfony.com/support).

The comments here should be used to discuss if and how the current documentation could be improved.

**Comment by elfring** [comment] 2021-03-24 13:50
>…, please create a fully working example application …

I have got a special view for this expectation.
I interpret parts of the source file “vendor/symfony/framework-bundle/Command/TranslationUpdateCommand.php” in the way that the search for translatable files would be restricted. The search filter might not fit to my application so far.


>If you need support with getting your application running, …

I am trying to achieve something by usual communication interfaces.


>The comments here should be used to discuss if and how the current documentation could be improved.

I guess that two areas can be improved here.
* PHP source code
* Corresponding documents

**Comment by xabbuh** [comment] 2021-03-24 13:53
I am out here...

**Comment by wouterj** [comment] 2021-03-24 14:07
As indicated by @xabbuh, this doesn't appear to be a documentation issue. As such, I'm closing this issue.

If you think you've hit a bug, please make sure that everyone is able to reproduce it. See also the documentation about [Creating a Bug Reproducer](https://symfony.com/doc/current/contributing/code/reproducer.html).

**Closed as completed by wouterj** 2021-03-24 14:07 UTC
Labels: Translation

**Comment by elfring** [comment] 2021-03-24 14:16
How much care can you give to translation process issues at the moment?

**Comment by wouterj** [comment] 2021-03-24 14:24
The same care as any other bug or issue with Symfony. However, without a reproducer, there is not much to fix for me. So either you have to debug the issue yourself and submit a fix, or you have to create something that allows me to reproduce it.

**Comment by elfring** [comment] 2021-03-25 12:31
Can we achieve a better understanding for supported directory structures?
