### ISSUE TITLE
Default Symfony stylesheet and js files missing

### ISSUE THREAD

**Issue by robfrawley** [symfony/symfony-docs#9308] opened 2018-02-21 21:43 UTC
The default Symfony documentation stylesheet `https://symfony.com/css/compiled/v5/all.css?v=4` and js `https://symfony.com/js/v5/all.js?v=4` files are no longer valid URLs; it looks like the new live Symfony documentation uses compiled stylesheet/js files, likely the result of `webkit`or `encore`.

While this is fine for the main website, we still need a consistent URL to point to for documentation PRs, as well as for local builds of documentation, including external projects that rely on this documentation (for example, local testing of the [liip/imagine-bundle](https://github.com/liip/LiipImagineBundle/wiki/Building-RST-Documentation) documentation now has no styling or javascript). Regarding this repository, all the current PRs show unstyled HTML on their platform.sh builds.

First, we need a static location for the compiled stylesheets and js to be exposed from the new build system, and then the lines that require updates in this repository are in [_build/_theme/_templates/layout.html](https://github.com/symfony/symfony-docs/blob/master/_build/_theme/_templates/layout.html), specifically [line 3](https://github.com/symfony/symfony-docs/blob/master/_build/_theme/_templates/layout.html#L3) and [line 10](https://github.com/symfony/symfony-docs/blob/master/_build/_theme/_templates/layout.html#L10).

**Comment by snoek09** [comment] 2018-03-15 22:05
duplicate of https://github.com/symfony/symfony-docs/issues/9246

**Comment by robfrawley** [comment] 2018-03-16 00:10
Not a duplicate of #9246, which focuses on *updating* the theme. This issue is the result of Symfony *removing* the default theme the documentation points to when built locally.

**Comment by snoek09** [comment] 2018-03-16 07:48
My bad, I rephrased it.

**Comment by javiereguiluz** [comment] 2018-05-28 09:30
This was fixed by #9517. If the error persist, please reopen and provide more details about the error (screenshots, error messages, URLs of CSS/JS files that can't be loaded, etc.) Thanks!

**Closed by javiereguiluz** 2018-05-28 09:30 UTC
Labels: Website, hasPR
