### ISSUE TITLE
Images are not shown for current SF version

### ISSUE THREAD

**Issue by Pierstoval** [symfony/symfony-docs#7550] opened 2017-03-01 08:55 UTC
Some images seem not to be working anymore, for pages relative to `current` Symfony version, like this:

https://symfony.com/doc/current/introduction/http_fundamentals.html

Seems to come from the redirection system:

```
curl -I https://symfony.com/doc/current/_images/xkcd-request.png
...
Location: /doc/3.2/_images/xkcd-request.png.html
```

**Comment by javiereguiluz** [comment] 2017-03-01 09:03
They are working for me. Anyone else has this problem?

**Comment by Pierstoval** [comment] 2017-03-01 09:39
When going on this url:
https://symfony.com/doc/current/introduction/http_fundamentals.html

I see this:
![image](https://cloud.githubusercontent.com/assets/3369266/23454050/2f95cd3e-fe6b-11e6-88f0-b87b2e089711.png)


But for 3.1 it works correctly:
https://symfony.com/doc/3.1/introduction/http_fundamentals.html
![image](https://cloud.githubusercontent.com/assets/3369266/23454078/52e4cfd8-fe6b-11e6-95d3-8ffbbb6317dc.png)

**Comment by javiereguiluz** [comment] 2017-03-01 10:00
Now I can reproduce it ... maybe it was a cache in my browser. Looking into it.

**Comment by javiereguiluz** [comment] 2017-03-01 10:55
Closing it as "fixed" because the images are working again. We're still investigating the root cause to make sure it never happens again. Thanks!

**Comment by Pierstoval** [comment] 2017-03-01 11:13
Cleared the cache and still does not work for me 😕

**Comment by xabbuh** [comment] 2017-03-01 11:29
same here

**Comment by CarlPham** [comment] 2017-03-02 07:32
![image](https://cloud.githubusercontent.com/assets/1766199/23497298/ff1faa90-ff54-11e6-9bd3-3d3a11d4da52.png)
me too

**Comment by miracle84** [comment] 2017-03-02 11:05
The same for me

**Comment by javiereguiluz** [comment] 2017-03-02 11:15
We're working on this ... but we are still trying to find out the cause of this problem 😕

**Comment by Pierstoval** [comment] 2017-03-02 12:06
It seems that the cause has been found and the team is preparing a fix for this, just stay tuned :)

**Comment by javiereguiluz** [comment] 2017-03-04 14:35
Closing it as "fixed" ... and this time I think it's for real 😊

**Closed by javiereguiluz** 2017-03-04 14:35 UTC
Labels: Bug, Status: Reviewed, Website

**Comment by Pierstoval** [comment] 2017-03-04 18:11
Yes it is 👍

**Comment by sustmi** [comment] 2017-05-30 08:20
The problem still occurs here: http://symfony.com/doc/current/doctrine.html#add-mapping-information

![docs-img](https://cloud.githubusercontent.com/assets/885946/26574289/12598146-4521-11e7-8052-46b163236412.png)

> We're still investigating the root cause to make sure it never happens again.

> Closing it as "fixed" ... and this time I think it's for real

Could you please explain what was/is the problem about?

**Comment by Pierstoval** [comment] 2017-05-30 08:36
@sustmi this time, works for me 😕

**Comment by sustmi** [comment] 2017-05-30 09:48
OK, this issue is really weird. I had to wipe last one hour of my Firefox cache and then it started to work. It looks like the first time my browser tried to download the image it got redirected to the error page and then it cached the result so when the file became available later it still shows that the image does not exist.

Maybe your Varnish is broken so that it does not return the correct response until it caches the image internally (after Varnish restart for example). Then when it caches the image it returns it but the browser has already cached the 301 redirect response so it no longer tries GET on the actual image.

The other theory I have in mind is that maybe you do some on-the-fly copying of images of from `3.2` to `current` that does not result in correct response on the first request.

**Comment by sustmi** [comment] 2017-05-30 10:07
Or maybe it is not connected to the first request anyhow but server just randomly fails to handle lets say every 1000th request. Browser then caches the redirect response and the person comes here to report it but nobody else is able to reproduce it because others are "not lucky enough".
